// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/zone/compiled.proto

package zone

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompiledZone is the binary format for pre-compiled DNS zones (.dzc files)
// This format is optimized for fast loading and query performance.
type CompiledZone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Zone metadata
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // Fully qualified zone name (e.g., "example.com.")
	Origin string `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"` // Same as name (for compatibility)
	Class  uint32 `protobuf:"varint,3,opt,name=class,proto3" json:"class,omitempty"`  // DNS class (typically 1 = IN)
	// SOA record (always present)
	Soa *SOARecord `protobuf:"bytes,4,opt,name=soa,proto3" json:"soa,omitempty"`
	// All records organized by owner name for fast lookup
	// Map: owner name -> RecordSet
	Records map[string]*RecordSet `protobuf:"bytes,5,rep,name=records,proto3" json:"records,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Owner name index (sorted for wildcard matching)
	OwnerIndex []string `protobuf:"bytes,6,rep,name=owner_index,json=ownerIndex,proto3" json:"owner_index,omitempty"`
	// Compilation metadata
	Metadata *CompilationMeta `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// DNSSEC configuration (if enabled)
	Dnssec *CompiledDNSSECConfig `protobuf:"bytes,8,opt,name=dnssec,proto3" json:"dnssec,omitempty"`
	// Pre-computed zone statistics
	Stats         *ZoneStats `protobuf:"bytes,9,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledZone) Reset() {
	*x = CompiledZone{}
	mi := &file_internal_zone_compiled_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledZone) ProtoMessage() {}

func (x *CompiledZone) ProtoReflect() protoreflect.Message {
	mi := &file_internal_zone_compiled_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledZone.ProtoReflect.Descriptor instead.
func (*CompiledZone) Descriptor() ([]byte, []int) {
	return file_internal_zone_compiled_proto_rawDescGZIP(), []int{0}
}

func (x *CompiledZone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompiledZone) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CompiledZone) GetClass() uint32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *CompiledZone) GetSoa() *SOARecord {
	if x != nil {
		return x.Soa
	}
	return nil
}

func (x *CompiledZone) GetRecords() map[string]*RecordSet {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *CompiledZone) GetOwnerIndex() []string {
	if x != nil {
		return x.OwnerIndex
	}
	return nil
}

func (x *CompiledZone) GetMetadata() *CompilationMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CompiledZone) GetDnssec() *CompiledDNSSECConfig {
	if x != nil {
		return x.Dnssec
	}
	return nil
}

func (x *CompiledZone) GetStats() *ZoneStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// SOARecord stores Start of Authority information
type SOARecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryNs     string                 `protobuf:"bytes,1,opt,name=primary_ns,json=primaryNs,proto3" json:"primary_ns,omitempty"`     // Primary nameserver
	AdminEmail    string                 `protobuf:"bytes,2,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`  // Admin email (in DNS format: admin.example.com.)
	Serial        uint32                 `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`                           // Zone serial number
	Refresh       uint32                 `protobuf:"varint,4,opt,name=refresh,proto3" json:"refresh,omitempty"`                         // Refresh interval (seconds)
	Retry         uint32                 `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`                             // Retry interval (seconds)
	Expire        uint32                 `protobuf:"varint,6,opt,name=expire,proto3" json:"expire,omitempty"`                           // Expire time (seconds)
	MinimumTtl    uint32                 `protobuf:"varint,7,opt,name=minimum_ttl,json=minimumTtl,proto3" json:"minimum_ttl,omitempty"` // Negative caching TTL
	Ttl           uint32                 `protobuf:"varint,8,opt,name=ttl,proto3" json:"ttl,omitempty"`                                 // SOA record TTL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SOARecord) Reset() {
	*x = SOARecord{}
	mi := &file_internal_zone_compiled_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SOARecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOARecord) ProtoMessage() {}

func (x *SOARecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_zone_compiled_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOARecord.ProtoReflect.Descriptor instead.
func (*SOARecord) Descriptor() ([]byte, []int) {
	return file_internal_zone_compiled_proto_rawDescGZIP(), []int{1}
}

func (x *SOARecord) GetPrimaryNs() string {
	if x != nil {
		return x.PrimaryNs
	}
	return ""
}

func (x *SOARecord) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *SOARecord) GetSerial() uint32 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *SOARecord) GetRefresh() uint32 {
	if x != nil {
		return x.Refresh
	}
	return 0
}

func (x *SOARecord) GetRetry() uint32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *SOARecord) GetExpire() uint32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *SOARecord) GetMinimumTtl() uint32 {
	if x != nil {
		return x.MinimumTtl
	}
	return 0
}

func (x *SOARecord) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// RecordSet contains all records for a specific owner name
type RecordSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map: record type (uint16) -> list of records
	// Type as string for protobuf compatibility
	Records       map[string]*RecordList `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSet) Reset() {
	*x = RecordSet{}
	mi := &file_internal_zone_compiled_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSet) ProtoMessage() {}

func (x *RecordSet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_zone_compiled_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSet.ProtoReflect.Descriptor instead.
func (*RecordSet) Descriptor() ([]byte, []int) {
	return file_internal_zone_compiled_proto_rawDescGZIP(), []int{2}
}

func (x *RecordSet) GetRecords() map[string]*RecordList {
	if x != nil {
		return x.Records
	}
	return nil
}

// RecordList contains multiple records of the same type
type RecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordList) Reset() {
	*x = RecordList{}
	mi := &file_internal_zone_compiled_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordList) ProtoMessage() {}

func (x *RecordList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_zone_compiled_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordList.ProtoReflect.Descriptor instead.
func (*RecordList) Descriptor() ([]byte, []int) {
	return file_internal_zone_compiled_proto_rawDescGZIP(), []int{3}
}

func (x *RecordList) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// Record represents a single DNS resource record
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // Owner name (FQDN)
	Type  uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`   // Record type (uint16)
	Class uint32                 `protobuf:"varint,3,opt,name=class,proto3" json:"class,omitempty"` // Record class (uint16)
	Ttl   uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`     // Time to live (seconds)
	// Wire-format record data (RDATA section)
	Rdata []byte `protobuf:"bytes,5,opt,name=rdata,proto3" json:"rdata,omitempty"`
	// Human-readable representation (for debugging)
	Text          string `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_internal_zone_compiled_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_internal_zone_compiled_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_internal_zone_compiled_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Record) GetClass() uint32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *Record) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Record) GetRdata() []byte {
	if x != nil {
		return x.Rdata
	}
	return nil
}

func (x *Record) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// CompilationMeta tracks compilation information
type CompilationMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format version (for backward compatibility)
	FormatVersion uint32 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"` // Current: 1
	// Source file information
	SourceFile   string `protobuf:"bytes,2,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`       // Original zone file path
	SourceFormat string `protobuf:"bytes,3,opt,name=source_format,json=sourceFormat,proto3" json:"source_format,omitempty"` // "dnszone", "bind", etc.
	SourceSha256 []byte `protobuf:"bytes,4,opt,name=source_sha256,json=sourceSha256,proto3" json:"source_sha256,omitempty"` // SHA-256 hash of source file
	// Compilation timestamps
	CompiledAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=compiled_at,json=compiledAt,proto3" json:"compiled_at,omitempty"`
	SourceModifiedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=source_modified_at,json=sourceModifiedAt,proto3" json:"source_modified_at,omitempty"`
	// Compiler information
	CompilerVersion string `protobuf:"bytes,7,opt,name=compiler_version,json=compilerVersion,proto3" json:"compiler_version,omitempty"` // dnsscienced version
	// Compilation options
	Options       map[string]string `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompilationMeta) Reset() {
	*x = CompilationMeta{}
	mi := &file_internal_zone_compiled_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilationMeta) ProtoMessage() {}

func (x *CompilationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_zone_compiled_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilationMeta.ProtoReflect.Descriptor instead.
func (*CompilationMeta) Descriptor() ([]byte, []int) {
	return file_internal_zone_compiled_proto_rawDescGZIP(), []int{5}
}

func (x *CompilationMeta) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *CompilationMeta) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *CompilationMeta) GetSourceFormat() string {
	if x != nil {
		return x.SourceFormat
	}
	return ""
}

func (x *CompilationMeta) GetSourceSha256() []byte {
	if x != nil {
		return x.SourceSha256
	}
	return nil
}

func (x *CompilationMeta) GetCompiledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompiledAt
	}
	return nil
}

func (x *CompilationMeta) GetSourceModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceModifiedAt
	}
	return nil
}

func (x *CompilationMeta) GetCompilerVersion() string {
	if x != nil {
		return x.CompilerVersion
	}
	return ""
}

func (x *CompilationMeta) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// CompiledDNSSECConfig stores DNSSEC settings in compiled format
type CompiledDNSSECConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enabled            bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Algorithm          uint32                 `protobuf:"varint,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // DNSSEC algorithm number
	KskLifetimeSeconds uint64                 `protobuf:"varint,3,opt,name=ksk_lifetime_seconds,json=kskLifetimeSeconds,proto3" json:"ksk_lifetime_seconds,omitempty"`
	ZskLifetimeSeconds uint64                 `protobuf:"varint,4,opt,name=zsk_lifetime_seconds,json=zskLifetimeSeconds,proto3" json:"zsk_lifetime_seconds,omitempty"`
	// NSEC3 parameters
	Nsec3         *NSEC3Params `protobuf:"bytes,5,opt,name=nsec3,proto3" json:"nsec3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledDNSSECConfig) Reset() {
	*x = CompiledDNSSECConfig{}
	mi := &file_internal_zone_compiled_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledDNSSECConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledDNSSECConfig) ProtoMessage() {}

func (x *CompiledDNSSECConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_zone_compiled_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledDNSSECConfig.ProtoReflect.Descriptor instead.
func (*CompiledDNSSECConfig) Descriptor() ([]byte, []int) {
	return file_internal_zone_compiled_proto_rawDescGZIP(), []int{6}
}

func (x *CompiledDNSSECConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CompiledDNSSECConfig) GetAlgorithm() uint32 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *CompiledDNSSECConfig) GetKskLifetimeSeconds() uint64 {
	if x != nil {
		return x.KskLifetimeSeconds
	}
	return 0
}

func (x *CompiledDNSSECConfig) GetZskLifetimeSeconds() uint64 {
	if x != nil {
		return x.ZskLifetimeSeconds
	}
	return 0
}

func (x *CompiledDNSSECConfig) GetNsec3() *NSEC3Params {
	if x != nil {
		return x.Nsec3
	}
	return nil
}

// NSEC3Params stores NSEC3 configuration
type NSEC3Params struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Iterations    uint32                 `protobuf:"varint,2,opt,name=iterations,proto3" json:"iterations,omitempty"`
	SaltLength    uint32                 `protobuf:"varint,3,opt,name=salt_length,json=saltLength,proto3" json:"salt_length,omitempty"`
	Salt          []byte                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"` // Current salt value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSEC3Params) Reset() {
	*x = NSEC3Params{}
	mi := &file_internal_zone_compiled_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSEC3Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSEC3Params) ProtoMessage() {}

func (x *NSEC3Params) ProtoReflect() protoreflect.Message {
	mi := &file_internal_zone_compiled_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSEC3Params.ProtoReflect.Descriptor instead.
func (*NSEC3Params) Descriptor() ([]byte, []int) {
	return file_internal_zone_compiled_proto_rawDescGZIP(), []int{7}
}

func (x *NSEC3Params) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NSEC3Params) GetIterations() uint32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *NSEC3Params) GetSaltLength() uint32 {
	if x != nil {
		return x.SaltLength
	}
	return 0
}

func (x *NSEC3Params) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

// ZoneStats pre-computed zone statistics
type ZoneStats struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RecordSets   uint32                 `protobuf:"varint,1,opt,name=record_sets,json=recordSets,proto3" json:"record_sets,omitempty"`       // Number of unique (owner, type) pairs
	TotalRecords uint32                 `protobuf:"varint,2,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"` // Total number of records
	UniqueOwners uint32                 `protobuf:"varint,3,opt,name=unique_owners,json=uniqueOwners,proto3" json:"unique_owners,omitempty"` // Number of unique owner names
	SizeBytes    uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`          // Compiled zone size in bytes
	// Record type distribution (for analytics)
	TypeCounts    map[string]uint32 `protobuf:"bytes,5,rep,name=type_counts,json=typeCounts,proto3" json:"type_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Type -> count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneStats) Reset() {
	*x = ZoneStats{}
	mi := &file_internal_zone_compiled_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneStats) ProtoMessage() {}

func (x *ZoneStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_zone_compiled_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneStats.ProtoReflect.Descriptor instead.
func (*ZoneStats) Descriptor() ([]byte, []int) {
	return file_internal_zone_compiled_proto_rawDescGZIP(), []int{8}
}

func (x *ZoneStats) GetRecordSets() uint32 {
	if x != nil {
		return x.RecordSets
	}
	return 0
}

func (x *ZoneStats) GetTotalRecords() uint32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *ZoneStats) GetUniqueOwners() uint32 {
	if x != nil {
		return x.UniqueOwners
	}
	return 0
}

func (x *ZoneStats) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ZoneStats) GetTypeCounts() map[string]uint32 {
	if x != nil {
		return x.TypeCounts
	}
	return nil
}

var File_internal_zone_compiled_proto protoreflect.FileDescriptor

const file_internal_zone_compiled_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/zone/compiled.proto\x12\x04zone\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x03\n" +
	"\fCompiledZone\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12\x14\n" +
	"\x05class\x18\x03 \x01(\rR\x05class\x12!\n" +
	"\x03soa\x18\x04 \x01(\v2\x0f.zone.SOARecordR\x03soa\x129\n" +
	"\arecords\x18\x05 \x03(\v2\x1f.zone.CompiledZone.RecordsEntryR\arecords\x12\x1f\n" +
	"\vowner_index\x18\x06 \x03(\tR\n" +
	"ownerIndex\x121\n" +
	"\bmetadata\x18\a \x01(\v2\x15.zone.CompilationMetaR\bmetadata\x122\n" +
	"\x06dnssec\x18\b \x01(\v2\x1a.zone.CompiledDNSSECConfigR\x06dnssec\x12%\n" +
	"\x05stats\x18\t \x01(\v2\x0f.zone.ZoneStatsR\x05stats\x1aK\n" +
	"\fRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.zone.RecordSetR\x05value:\x028\x01\"\xde\x01\n" +
	"\tSOARecord\x12\x1d\n" +
	"\n" +
	"primary_ns\x18\x01 \x01(\tR\tprimaryNs\x12\x1f\n" +
	"\vadmin_email\x18\x02 \x01(\tR\n" +
	"adminEmail\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\rR\x06serial\x12\x18\n" +
	"\arefresh\x18\x04 \x01(\rR\arefresh\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\rR\x05retry\x12\x16\n" +
	"\x06expire\x18\x06 \x01(\rR\x06expire\x12\x1f\n" +
	"\vminimum_ttl\x18\a \x01(\rR\n" +
	"minimumTtl\x12\x10\n" +
	"\x03ttl\x18\b \x01(\rR\x03ttl\"\x91\x01\n" +
	"\tRecordSet\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.zone.RecordSet.RecordsEntryR\arecords\x1aL\n" +
	"\fRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.zone.RecordListR\x05value:\x028\x01\"4\n" +
	"\n" +
	"RecordList\x12&\n" +
	"\arecords\x18\x01 \x03(\v2\f.zone.RecordR\arecords\"\x82\x01\n" +
	"\x06Record\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x14\n" +
	"\x05class\x18\x03 \x01(\rR\x05class\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x14\n" +
	"\x05rdata\x18\x05 \x01(\fR\x05rdata\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\"\xcf\x03\n" +
	"\x0fCompilationMeta\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x1f\n" +
	"\vsource_file\x18\x02 \x01(\tR\n" +
	"sourceFile\x12#\n" +
	"\rsource_format\x18\x03 \x01(\tR\fsourceFormat\x12#\n" +
	"\rsource_sha256\x18\x04 \x01(\fR\fsourceSha256\x12;\n" +
	"\vcompiled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"compiledAt\x12H\n" +
	"\x12source_modified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10sourceModifiedAt\x12)\n" +
	"\x10compiler_version\x18\a \x01(\tR\x0fcompilerVersion\x12<\n" +
	"\aoptions\x18\b \x03(\v2\".zone.CompilationMeta.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x14CompiledDNSSECConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\rR\talgorithm\x120\n" +
	"\x14ksk_lifetime_seconds\x18\x03 \x01(\x04R\x12kskLifetimeSeconds\x120\n" +
	"\x14zsk_lifetime_seconds\x18\x04 \x01(\x04R\x12zskLifetimeSeconds\x12'\n" +
	"\x05nsec3\x18\x05 \x01(\v2\x11.zone.NSEC3ParamsR\x05nsec3\"|\n" +
	"\vNSEC3Params\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1e\n" +
	"\n" +
	"iterations\x18\x02 \x01(\rR\n" +
	"iterations\x12\x1f\n" +
	"\vsalt_length\x18\x03 \x01(\rR\n" +
	"saltLength\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\fR\x04salt\"\x96\x02\n" +
	"\tZoneStats\x12\x1f\n" +
	"\vrecord_sets\x18\x01 \x01(\rR\n" +
	"recordSets\x12#\n" +
	"\rtotal_records\x18\x02 \x01(\rR\ftotalRecords\x12#\n" +
	"\runique_owners\x18\x03 \x01(\rR\funiqueOwners\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12@\n" +
	"\vtype_counts\x18\x05 \x03(\v2\x1f.zone.ZoneStats.TypeCountsEntryR\n" +
	"typeCounts\x1a=\n" +
	"\x0fTypeCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01B1Z/github.com/dnsscience/dnsscienced/internal/zoneb\x06proto3"

var (
	file_internal_zone_compiled_proto_rawDescOnce sync.Once
	file_internal_zone_compiled_proto_rawDescData []byte
)

func file_internal_zone_compiled_proto_rawDescGZIP() []byte {
	file_internal_zone_compiled_proto_rawDescOnce.Do(func() {
		file_internal_zone_compiled_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_zone_compiled_proto_rawDesc), len(file_internal_zone_compiled_proto_rawDesc)))
	})
	return file_internal_zone_compiled_proto_rawDescData
}

var file_internal_zone_compiled_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_zone_compiled_proto_goTypes = []any{
	(*CompiledZone)(nil),          // 0: zone.CompiledZone
	(*SOARecord)(nil),             // 1: zone.SOARecord
	(*RecordSet)(nil),             // 2: zone.RecordSet
	(*RecordList)(nil),            // 3: zone.RecordList
	(*Record)(nil),                // 4: zone.Record
	(*CompilationMeta)(nil),       // 5: zone.CompilationMeta
	(*CompiledDNSSECConfig)(nil),  // 6: zone.CompiledDNSSECConfig
	(*NSEC3Params)(nil),           // 7: zone.NSEC3Params
	(*ZoneStats)(nil),             // 8: zone.ZoneStats
	nil,                           // 9: zone.CompiledZone.RecordsEntry
	nil,                           // 10: zone.RecordSet.RecordsEntry
	nil,                           // 11: zone.CompilationMeta.OptionsEntry
	nil,                           // 12: zone.ZoneStats.TypeCountsEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_internal_zone_compiled_proto_depIdxs = []int32{
	1,  // 0: zone.CompiledZone.soa:type_name -> zone.SOARecord
	9,  // 1: zone.CompiledZone.records:type_name -> zone.CompiledZone.RecordsEntry
	5,  // 2: zone.CompiledZone.metadata:type_name -> zone.CompilationMeta
	6,  // 3: zone.CompiledZone.dnssec:type_name -> zone.CompiledDNSSECConfig
	8,  // 4: zone.CompiledZone.stats:type_name -> zone.ZoneStats
	10, // 5: zone.RecordSet.records:type_name -> zone.RecordSet.RecordsEntry
	4,  // 6: zone.RecordList.records:type_name -> zone.Record
	13, // 7: zone.CompilationMeta.compiled_at:type_name -> google.protobuf.Timestamp
	13, // 8: zone.CompilationMeta.source_modified_at:type_name -> google.protobuf.Timestamp
	11, // 9: zone.CompilationMeta.options:type_name -> zone.CompilationMeta.OptionsEntry
	7,  // 10: zone.CompiledDNSSECConfig.nsec3:type_name -> zone.NSEC3Params
	12, // 11: zone.ZoneStats.type_counts:type_name -> zone.ZoneStats.TypeCountsEntry
	2,  // 12: zone.CompiledZone.RecordsEntry.value:type_name -> zone.RecordSet
	3,  // 13: zone.RecordSet.RecordsEntry.value:type_name -> zone.RecordList
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_internal_zone_compiled_proto_init() }
func file_internal_zone_compiled_proto_init() {
	if File_internal_zone_compiled_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_zone_compiled_proto_rawDesc), len(file_internal_zone_compiled_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_zone_compiled_proto_goTypes,
		DependencyIndexes: file_internal_zone_compiled_proto_depIdxs,
		MessageInfos:      file_internal_zone_compiled_proto_msgTypes,
	}.Build()
	File_internal_zone_compiled_proto = out.File
	file_internal_zone_compiled_proto_goTypes = nil
	file_internal_zone_compiled_proto_depIdxs = nil
}
