// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: admin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_FlushCache_FullMethodName            = "/dnsscience.v1.AdminService/FlushCache"
	AdminService_GetCacheStats_FullMethodName         = "/dnsscience.v1.AdminService/GetCacheStats"
	AdminService_PurgeCache_FullMethodName            = "/dnsscience.v1.AdminService/PurgeCache"
	AdminService_RefreshZone_FullMethodName           = "/dnsscience.v1.AdminService/RefreshZone"
	AdminService_ListZones_FullMethodName             = "/dnsscience.v1.AdminService/ListZones"
	AdminService_ReloadZones_FullMethodName           = "/dnsscience.v1.AdminService/ReloadZones"
	AdminService_CreateZone_FullMethodName            = "/dnsscience.v1.AdminService/CreateZone"
	AdminService_UpdateZone_FullMethodName            = "/dnsscience.v1.AdminService/UpdateZone"
	AdminService_DeleteZone_FullMethodName            = "/dnsscience.v1.AdminService/DeleteZone"
	AdminService_GetZone_FullMethodName               = "/dnsscience.v1.AdminService/GetZone"
	AdminService_CreateRecord_FullMethodName          = "/dnsscience.v1.AdminService/CreateRecord"
	AdminService_UpdateRecord_FullMethodName          = "/dnsscience.v1.AdminService/UpdateRecord"
	AdminService_DeleteRecord_FullMethodName          = "/dnsscience.v1.AdminService/DeleteRecord"
	AdminService_ListRecords_FullMethodName           = "/dnsscience.v1.AdminService/ListRecords"
	AdminService_SetQueryLogging_FullMethodName       = "/dnsscience.v1.AdminService/SetQueryLogging"
	AdminService_GetQueryLoggingStatus_FullMethodName = "/dnsscience.v1.AdminService/GetQueryLoggingStatus"
	AdminService_SetRateLimit_FullMethodName          = "/dnsscience.v1.AdminService/SetRateLimit"
	AdminService_GetRateLimitStatus_FullMethodName    = "/dnsscience.v1.AdminService/GetRateLimitStatus"
	AdminService_GetServerStatus_FullMethodName       = "/dnsscience.v1.AdminService/GetServerStatus"
	AdminService_GetMetrics_FullMethodName            = "/dnsscience.v1.AdminService/GetMetrics"
	AdminService_ShutdownServer_FullMethodName        = "/dnsscience.v1.AdminService/ShutdownServer"
	AdminService_ListConnections_FullMethodName       = "/dnsscience.v1.AdminService/ListConnections"
	AdminService_KillConnection_FullMethodName        = "/dnsscience.v1.AdminService/KillConnection"
	AdminService_AddTsigKey_FullMethodName            = "/dnsscience.v1.AdminService/AddTsigKey"
	AdminService_RemoveTsigKey_FullMethodName         = "/dnsscience.v1.AdminService/RemoveTsigKey"
	AdminService_ListTsigKeys_FullMethodName          = "/dnsscience.v1.AdminService/ListTsigKeys"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService provides control plane operations for DNSScienced
type AdminServiceClient interface {
	// Cache operations
	FlushCache(ctx context.Context, in *AdminFlushCacheRequest, opts ...grpc.CallOption) (*AdminFlushCacheResponse, error)
	GetCacheStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminCacheStatsResponse, error)
	PurgeCache(ctx context.Context, in *AdminPurgeCacheRequest, opts ...grpc.CallOption) (*AdminPurgeCacheResponse, error)
	// Zone operations
	RefreshZone(ctx context.Context, in *AdminRefreshZoneRequest, opts ...grpc.CallOption) (*AdminRefreshZoneResponse, error)
	ListZones(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminListZonesResponse, error)
	ReloadZones(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminReloadZonesResponse, error)
	// Zone management (create/update/delete)
	CreateZone(ctx context.Context, in *AdminCreateZoneRequest, opts ...grpc.CallOption) (*AdminCreateZoneResponse, error)
	UpdateZone(ctx context.Context, in *AdminUpdateZoneRequest, opts ...grpc.CallOption) (*AdminUpdateZoneResponse, error)
	DeleteZone(ctx context.Context, in *AdminDeleteZoneRequest, opts ...grpc.CallOption) (*AdminDeleteZoneResponse, error)
	GetZone(ctx context.Context, in *AdminGetZoneRequest, opts ...grpc.CallOption) (*AdminGetZoneResponse, error)
	// Record management
	CreateRecord(ctx context.Context, in *AdminCreateRecordRequest, opts ...grpc.CallOption) (*AdminCreateRecordResponse, error)
	UpdateRecord(ctx context.Context, in *AdminUpdateRecordRequest, opts ...grpc.CallOption) (*AdminUpdateRecordResponse, error)
	DeleteRecord(ctx context.Context, in *AdminDeleteRecordRequest, opts ...grpc.CallOption) (*AdminDeleteRecordResponse, error)
	ListRecords(ctx context.Context, in *AdminListRecordsRequest, opts ...grpc.CallOption) (*AdminListRecordsResponse, error)
	// Query logging control
	SetQueryLogging(ctx context.Context, in *AdminSetQueryLoggingRequest, opts ...grpc.CallOption) (*AdminSetQueryLoggingResponse, error)
	GetQueryLoggingStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminQueryLoggingStatusResponse, error)
	// Rate limiting control
	SetRateLimit(ctx context.Context, in *AdminSetRateLimitRequest, opts ...grpc.CallOption) (*AdminSetRateLimitResponse, error)
	GetRateLimitStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminRateLimitStatusResponse, error)
	// Server control
	GetServerStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminServerStatusResponse, error)
	GetMetrics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminMetricsResponse, error)
	ShutdownServer(ctx context.Context, in *AdminShutdownRequest, opts ...grpc.CallOption) (*AdminShutdownResponse, error)
	// Connection management
	ListConnections(ctx context.Context, in *AdminListConnectionsRequest, opts ...grpc.CallOption) (*AdminListConnectionsResponse, error)
	KillConnection(ctx context.Context, in *AdminKillConnectionRequest, opts ...grpc.CallOption) (*AdminKillConnectionResponse, error)
	// TSIG Key Management (RFC 2845)
	AddTsigKey(ctx context.Context, in *AdminAddTsigKeyRequest, opts ...grpc.CallOption) (*AdminAddTsigKeyResponse, error)
	RemoveTsigKey(ctx context.Context, in *AdminRemoveTsigKeyRequest, opts ...grpc.CallOption) (*AdminRemoveTsigKeyResponse, error)
	ListTsigKeys(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminListTsigKeysResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) FlushCache(ctx context.Context, in *AdminFlushCacheRequest, opts ...grpc.CallOption) (*AdminFlushCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminFlushCacheResponse)
	err := c.cc.Invoke(ctx, AdminService_FlushCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetCacheStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminCacheStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCacheStatsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetCacheStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PurgeCache(ctx context.Context, in *AdminPurgeCacheRequest, opts ...grpc.CallOption) (*AdminPurgeCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPurgeCacheResponse)
	err := c.cc.Invoke(ctx, AdminService_PurgeCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RefreshZone(ctx context.Context, in *AdminRefreshZoneRequest, opts ...grpc.CallOption) (*AdminRefreshZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRefreshZoneResponse)
	err := c.cc.Invoke(ctx, AdminService_RefreshZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListZones(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminListZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListZonesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ReloadZones(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminReloadZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminReloadZonesResponse)
	err := c.cc.Invoke(ctx, AdminService_ReloadZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateZone(ctx context.Context, in *AdminCreateZoneRequest, opts ...grpc.CallOption) (*AdminCreateZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateZoneResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateZone(ctx context.Context, in *AdminUpdateZoneRequest, opts ...grpc.CallOption) (*AdminUpdateZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdateZoneResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteZone(ctx context.Context, in *AdminDeleteZoneRequest, opts ...grpc.CallOption) (*AdminDeleteZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteZoneResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetZone(ctx context.Context, in *AdminGetZoneRequest, opts ...grpc.CallOption) (*AdminGetZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminGetZoneResponse)
	err := c.cc.Invoke(ctx, AdminService_GetZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateRecord(ctx context.Context, in *AdminCreateRecordRequest, opts ...grpc.CallOption) (*AdminCreateRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateRecordResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateRecord(ctx context.Context, in *AdminUpdateRecordRequest, opts ...grpc.CallOption) (*AdminUpdateRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdateRecordResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteRecord(ctx context.Context, in *AdminDeleteRecordRequest, opts ...grpc.CallOption) (*AdminDeleteRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteRecordResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListRecords(ctx context.Context, in *AdminListRecordsRequest, opts ...grpc.CallOption) (*AdminListRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListRecordsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetQueryLogging(ctx context.Context, in *AdminSetQueryLoggingRequest, opts ...grpc.CallOption) (*AdminSetQueryLoggingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminSetQueryLoggingResponse)
	err := c.cc.Invoke(ctx, AdminService_SetQueryLogging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetQueryLoggingStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminQueryLoggingStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminQueryLoggingStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetQueryLoggingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetRateLimit(ctx context.Context, in *AdminSetRateLimitRequest, opts ...grpc.CallOption) (*AdminSetRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminSetRateLimitResponse)
	err := c.cc.Invoke(ctx, AdminService_SetRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetRateLimitStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminRateLimitStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRateLimitStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetRateLimitStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetServerStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminServerStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetMetrics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminMetricsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ShutdownServer(ctx context.Context, in *AdminShutdownRequest, opts ...grpc.CallOption) (*AdminShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminShutdownResponse)
	err := c.cc.Invoke(ctx, AdminService_ShutdownServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListConnections(ctx context.Context, in *AdminListConnectionsRequest, opts ...grpc.CallOption) (*AdminListConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListConnectionsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) KillConnection(ctx context.Context, in *AdminKillConnectionRequest, opts ...grpc.CallOption) (*AdminKillConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminKillConnectionResponse)
	err := c.cc.Invoke(ctx, AdminService_KillConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AddTsigKey(ctx context.Context, in *AdminAddTsigKeyRequest, opts ...grpc.CallOption) (*AdminAddTsigKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAddTsigKeyResponse)
	err := c.cc.Invoke(ctx, AdminService_AddTsigKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RemoveTsigKey(ctx context.Context, in *AdminRemoveTsigKeyRequest, opts ...grpc.CallOption) (*AdminRemoveTsigKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRemoveTsigKeyResponse)
	err := c.cc.Invoke(ctx, AdminService_RemoveTsigKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListTsigKeys(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AdminListTsigKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListTsigKeysResponse)
	err := c.cc.Invoke(ctx, AdminService_ListTsigKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService provides control plane operations for DNSScienced
type AdminServiceServer interface {
	// Cache operations
	FlushCache(context.Context, *AdminFlushCacheRequest) (*AdminFlushCacheResponse, error)
	GetCacheStats(context.Context, *emptypb.Empty) (*AdminCacheStatsResponse, error)
	PurgeCache(context.Context, *AdminPurgeCacheRequest) (*AdminPurgeCacheResponse, error)
	// Zone operations
	RefreshZone(context.Context, *AdminRefreshZoneRequest) (*AdminRefreshZoneResponse, error)
	ListZones(context.Context, *emptypb.Empty) (*AdminListZonesResponse, error)
	ReloadZones(context.Context, *emptypb.Empty) (*AdminReloadZonesResponse, error)
	// Zone management (create/update/delete)
	CreateZone(context.Context, *AdminCreateZoneRequest) (*AdminCreateZoneResponse, error)
	UpdateZone(context.Context, *AdminUpdateZoneRequest) (*AdminUpdateZoneResponse, error)
	DeleteZone(context.Context, *AdminDeleteZoneRequest) (*AdminDeleteZoneResponse, error)
	GetZone(context.Context, *AdminGetZoneRequest) (*AdminGetZoneResponse, error)
	// Record management
	CreateRecord(context.Context, *AdminCreateRecordRequest) (*AdminCreateRecordResponse, error)
	UpdateRecord(context.Context, *AdminUpdateRecordRequest) (*AdminUpdateRecordResponse, error)
	DeleteRecord(context.Context, *AdminDeleteRecordRequest) (*AdminDeleteRecordResponse, error)
	ListRecords(context.Context, *AdminListRecordsRequest) (*AdminListRecordsResponse, error)
	// Query logging control
	SetQueryLogging(context.Context, *AdminSetQueryLoggingRequest) (*AdminSetQueryLoggingResponse, error)
	GetQueryLoggingStatus(context.Context, *emptypb.Empty) (*AdminQueryLoggingStatusResponse, error)
	// Rate limiting control
	SetRateLimit(context.Context, *AdminSetRateLimitRequest) (*AdminSetRateLimitResponse, error)
	GetRateLimitStatus(context.Context, *emptypb.Empty) (*AdminRateLimitStatusResponse, error)
	// Server control
	GetServerStatus(context.Context, *emptypb.Empty) (*AdminServerStatusResponse, error)
	GetMetrics(context.Context, *emptypb.Empty) (*AdminMetricsResponse, error)
	ShutdownServer(context.Context, *AdminShutdownRequest) (*AdminShutdownResponse, error)
	// Connection management
	ListConnections(context.Context, *AdminListConnectionsRequest) (*AdminListConnectionsResponse, error)
	KillConnection(context.Context, *AdminKillConnectionRequest) (*AdminKillConnectionResponse, error)
	// TSIG Key Management (RFC 2845)
	AddTsigKey(context.Context, *AdminAddTsigKeyRequest) (*AdminAddTsigKeyResponse, error)
	RemoveTsigKey(context.Context, *AdminRemoveTsigKeyRequest) (*AdminRemoveTsigKeyResponse, error)
	ListTsigKeys(context.Context, *emptypb.Empty) (*AdminListTsigKeysResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) FlushCache(context.Context, *AdminFlushCacheRequest) (*AdminFlushCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushCache not implemented")
}
func (UnimplementedAdminServiceServer) GetCacheStats(context.Context, *emptypb.Empty) (*AdminCacheStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCacheStats not implemented")
}
func (UnimplementedAdminServiceServer) PurgeCache(context.Context, *AdminPurgeCacheRequest) (*AdminPurgeCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeCache not implemented")
}
func (UnimplementedAdminServiceServer) RefreshZone(context.Context, *AdminRefreshZoneRequest) (*AdminRefreshZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshZone not implemented")
}
func (UnimplementedAdminServiceServer) ListZones(context.Context, *emptypb.Empty) (*AdminListZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListZones not implemented")
}
func (UnimplementedAdminServiceServer) ReloadZones(context.Context, *emptypb.Empty) (*AdminReloadZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadZones not implemented")
}
func (UnimplementedAdminServiceServer) CreateZone(context.Context, *AdminCreateZoneRequest) (*AdminCreateZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateZone not implemented")
}
func (UnimplementedAdminServiceServer) UpdateZone(context.Context, *AdminUpdateZoneRequest) (*AdminUpdateZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateZone not implemented")
}
func (UnimplementedAdminServiceServer) DeleteZone(context.Context, *AdminDeleteZoneRequest) (*AdminDeleteZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteZone not implemented")
}
func (UnimplementedAdminServiceServer) GetZone(context.Context, *AdminGetZoneRequest) (*AdminGetZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetZone not implemented")
}
func (UnimplementedAdminServiceServer) CreateRecord(context.Context, *AdminCreateRecordRequest) (*AdminCreateRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRecord not implemented")
}
func (UnimplementedAdminServiceServer) UpdateRecord(context.Context, *AdminUpdateRecordRequest) (*AdminUpdateRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecord not implemented")
}
func (UnimplementedAdminServiceServer) DeleteRecord(context.Context, *AdminDeleteRecordRequest) (*AdminDeleteRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecord not implemented")
}
func (UnimplementedAdminServiceServer) ListRecords(context.Context, *AdminListRecordsRequest) (*AdminListRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedAdminServiceServer) SetQueryLogging(context.Context, *AdminSetQueryLoggingRequest) (*AdminSetQueryLoggingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetQueryLogging not implemented")
}
func (UnimplementedAdminServiceServer) GetQueryLoggingStatus(context.Context, *emptypb.Empty) (*AdminQueryLoggingStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueryLoggingStatus not implemented")
}
func (UnimplementedAdminServiceServer) SetRateLimit(context.Context, *AdminSetRateLimitRequest) (*AdminSetRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRateLimit not implemented")
}
func (UnimplementedAdminServiceServer) GetRateLimitStatus(context.Context, *emptypb.Empty) (*AdminRateLimitStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRateLimitStatus not implemented")
}
func (UnimplementedAdminServiceServer) GetServerStatus(context.Context, *emptypb.Empty) (*AdminServerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedAdminServiceServer) GetMetrics(context.Context, *emptypb.Empty) (*AdminMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedAdminServiceServer) ShutdownServer(context.Context, *AdminShutdownRequest) (*AdminShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShutdownServer not implemented")
}
func (UnimplementedAdminServiceServer) ListConnections(context.Context, *AdminListConnectionsRequest) (*AdminListConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedAdminServiceServer) KillConnection(context.Context, *AdminKillConnectionRequest) (*AdminKillConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillConnection not implemented")
}
func (UnimplementedAdminServiceServer) AddTsigKey(context.Context, *AdminAddTsigKeyRequest) (*AdminAddTsigKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTsigKey not implemented")
}
func (UnimplementedAdminServiceServer) RemoveTsigKey(context.Context, *AdminRemoveTsigKeyRequest) (*AdminRemoveTsigKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTsigKey not implemented")
}
func (UnimplementedAdminServiceServer) ListTsigKeys(context.Context, *emptypb.Empty) (*AdminListTsigKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTsigKeys not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_FlushCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminFlushCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).FlushCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_FlushCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).FlushCache(ctx, req.(*AdminFlushCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetCacheStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetCacheStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetCacheStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetCacheStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PurgeCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPurgeCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PurgeCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PurgeCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PurgeCache(ctx, req.(*AdminPurgeCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RefreshZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRefreshZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RefreshZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RefreshZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RefreshZone(ctx, req.(*AdminRefreshZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListZones(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ReloadZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ReloadZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ReloadZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ReloadZones(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateZone(ctx, req.(*AdminCreateZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateZone(ctx, req.(*AdminUpdateZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteZone(ctx, req.(*AdminDeleteZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetZone(ctx, req.(*AdminGetZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateRecord(ctx, req.(*AdminCreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateRecord(ctx, req.(*AdminUpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteRecord(ctx, req.(*AdminDeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListRecords(ctx, req.(*AdminListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetQueryLogging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminSetQueryLoggingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetQueryLogging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetQueryLogging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetQueryLogging(ctx, req.(*AdminSetQueryLoggingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetQueryLoggingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetQueryLoggingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetQueryLoggingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetQueryLoggingStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminSetRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetRateLimit(ctx, req.(*AdminSetRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetRateLimitStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetRateLimitStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetRateLimitStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetRateLimitStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetServerStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetMetrics(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ShutdownServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ShutdownServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ShutdownServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ShutdownServer(ctx, req.(*AdminShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListConnections(ctx, req.(*AdminListConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_KillConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminKillConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).KillConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_KillConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).KillConnection(ctx, req.(*AdminKillConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AddTsigKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAddTsigKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AddTsigKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AddTsigKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AddTsigKey(ctx, req.(*AdminAddTsigKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RemoveTsigKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRemoveTsigKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RemoveTsigKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RemoveTsigKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RemoveTsigKey(ctx, req.(*AdminRemoveTsigKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListTsigKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListTsigKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListTsigKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListTsigKeys(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsscience.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FlushCache",
			Handler:    _AdminService_FlushCache_Handler,
		},
		{
			MethodName: "GetCacheStats",
			Handler:    _AdminService_GetCacheStats_Handler,
		},
		{
			MethodName: "PurgeCache",
			Handler:    _AdminService_PurgeCache_Handler,
		},
		{
			MethodName: "RefreshZone",
			Handler:    _AdminService_RefreshZone_Handler,
		},
		{
			MethodName: "ListZones",
			Handler:    _AdminService_ListZones_Handler,
		},
		{
			MethodName: "ReloadZones",
			Handler:    _AdminService_ReloadZones_Handler,
		},
		{
			MethodName: "CreateZone",
			Handler:    _AdminService_CreateZone_Handler,
		},
		{
			MethodName: "UpdateZone",
			Handler:    _AdminService_UpdateZone_Handler,
		},
		{
			MethodName: "DeleteZone",
			Handler:    _AdminService_DeleteZone_Handler,
		},
		{
			MethodName: "GetZone",
			Handler:    _AdminService_GetZone_Handler,
		},
		{
			MethodName: "CreateRecord",
			Handler:    _AdminService_CreateRecord_Handler,
		},
		{
			MethodName: "UpdateRecord",
			Handler:    _AdminService_UpdateRecord_Handler,
		},
		{
			MethodName: "DeleteRecord",
			Handler:    _AdminService_DeleteRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _AdminService_ListRecords_Handler,
		},
		{
			MethodName: "SetQueryLogging",
			Handler:    _AdminService_SetQueryLogging_Handler,
		},
		{
			MethodName: "GetQueryLoggingStatus",
			Handler:    _AdminService_GetQueryLoggingStatus_Handler,
		},
		{
			MethodName: "SetRateLimit",
			Handler:    _AdminService_SetRateLimit_Handler,
		},
		{
			MethodName: "GetRateLimitStatus",
			Handler:    _AdminService_GetRateLimitStatus_Handler,
		},
		{
			MethodName: "GetServerStatus",
			Handler:    _AdminService_GetServerStatus_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _AdminService_GetMetrics_Handler,
		},
		{
			MethodName: "ShutdownServer",
			Handler:    _AdminService_ShutdownServer_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _AdminService_ListConnections_Handler,
		},
		{
			MethodName: "KillConnection",
			Handler:    _AdminService_KillConnection_Handler,
		},
		{
			MethodName: "AddTsigKey",
			Handler:    _AdminService_AddTsigKey_Handler,
		},
		{
			MethodName: "RemoveTsigKey",
			Handler:    _AdminService_RemoveTsigKey_Handler,
		},
		{
			MethodName: "ListTsigKeys",
			Handler:    _AdminService_ListTsigKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}

const (
	FirewallAdminService_FirewallStats_FullMethodName = "/dnsscience.v1.FirewallAdminService/FirewallStats"
	FirewallAdminService_LoadScript_FullMethodName    = "/dnsscience.v1.FirewallAdminService/LoadScript"
	FirewallAdminService_RemoveScript_FullMethodName  = "/dnsscience.v1.FirewallAdminService/RemoveScript"
	FirewallAdminService_InjectScore_FullMethodName   = "/dnsscience.v1.FirewallAdminService/InjectScore"
)

// FirewallAdminServiceClient is the client API for FirewallAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FirewallAdminService exposes firewall management operations over gRPC.
// Additive to AdminService — registered on the same admin gRPC server port.
type FirewallAdminServiceClient interface {
	FirewallStats(ctx context.Context, in *FirewallStatsRequest, opts ...grpc.CallOption) (*FirewallStatsResponse, error)
	LoadScript(ctx context.Context, in *FirewallLoadScriptRequest, opts ...grpc.CallOption) (*FirewallLoadScriptResponse, error)
	RemoveScript(ctx context.Context, in *FirewallRemoveScriptRequest, opts ...grpc.CallOption) (*FirewallRemoveScriptResponse, error)
	InjectScore(ctx context.Context, in *FirewallInjectScoreRequest, opts ...grpc.CallOption) (*FirewallInjectScoreResponse, error)
}

type firewallAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFirewallAdminServiceClient(cc grpc.ClientConnInterface) FirewallAdminServiceClient {
	return &firewallAdminServiceClient{cc}
}

func (c *firewallAdminServiceClient) FirewallStats(ctx context.Context, in *FirewallStatsRequest, opts ...grpc.CallOption) (*FirewallStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallStatsResponse)
	err := c.cc.Invoke(ctx, FirewallAdminService_FirewallStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallAdminServiceClient) LoadScript(ctx context.Context, in *FirewallLoadScriptRequest, opts ...grpc.CallOption) (*FirewallLoadScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallLoadScriptResponse)
	err := c.cc.Invoke(ctx, FirewallAdminService_LoadScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallAdminServiceClient) RemoveScript(ctx context.Context, in *FirewallRemoveScriptRequest, opts ...grpc.CallOption) (*FirewallRemoveScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallRemoveScriptResponse)
	err := c.cc.Invoke(ctx, FirewallAdminService_RemoveScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallAdminServiceClient) InjectScore(ctx context.Context, in *FirewallInjectScoreRequest, opts ...grpc.CallOption) (*FirewallInjectScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallInjectScoreResponse)
	err := c.cc.Invoke(ctx, FirewallAdminService_InjectScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirewallAdminServiceServer is the server API for FirewallAdminService service.
// All implementations must embed UnimplementedFirewallAdminServiceServer
// for forward compatibility.
//
// FirewallAdminService exposes firewall management operations over gRPC.
// Additive to AdminService — registered on the same admin gRPC server port.
type FirewallAdminServiceServer interface {
	FirewallStats(context.Context, *FirewallStatsRequest) (*FirewallStatsResponse, error)
	LoadScript(context.Context, *FirewallLoadScriptRequest) (*FirewallLoadScriptResponse, error)
	RemoveScript(context.Context, *FirewallRemoveScriptRequest) (*FirewallRemoveScriptResponse, error)
	InjectScore(context.Context, *FirewallInjectScoreRequest) (*FirewallInjectScoreResponse, error)
	mustEmbedUnimplementedFirewallAdminServiceServer()
}

// UnimplementedFirewallAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFirewallAdminServiceServer struct{}

func (UnimplementedFirewallAdminServiceServer) FirewallStats(context.Context, *FirewallStatsRequest) (*FirewallStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FirewallStats not implemented")
}
func (UnimplementedFirewallAdminServiceServer) LoadScript(context.Context, *FirewallLoadScriptRequest) (*FirewallLoadScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadScript not implemented")
}
func (UnimplementedFirewallAdminServiceServer) RemoveScript(context.Context, *FirewallRemoveScriptRequest) (*FirewallRemoveScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveScript not implemented")
}
func (UnimplementedFirewallAdminServiceServer) InjectScore(context.Context, *FirewallInjectScoreRequest) (*FirewallInjectScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectScore not implemented")
}
func (UnimplementedFirewallAdminServiceServer) mustEmbedUnimplementedFirewallAdminServiceServer() {}
func (UnimplementedFirewallAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeFirewallAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirewallAdminServiceServer will
// result in compilation errors.
type UnsafeFirewallAdminServiceServer interface {
	mustEmbedUnimplementedFirewallAdminServiceServer()
}

func RegisterFirewallAdminServiceServer(s grpc.ServiceRegistrar, srv FirewallAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedFirewallAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FirewallAdminService_ServiceDesc, srv)
}

func _FirewallAdminService_FirewallStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallAdminServiceServer).FirewallStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallAdminService_FirewallStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallAdminServiceServer).FirewallStats(ctx, req.(*FirewallStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallAdminService_LoadScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallLoadScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallAdminServiceServer).LoadScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallAdminService_LoadScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallAdminServiceServer).LoadScript(ctx, req.(*FirewallLoadScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallAdminService_RemoveScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallRemoveScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallAdminServiceServer).RemoveScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallAdminService_RemoveScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallAdminServiceServer).RemoveScript(ctx, req.(*FirewallRemoveScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallAdminService_InjectScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallInjectScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallAdminServiceServer).InjectScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallAdminService_InjectScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallAdminServiceServer).InjectScore(ctx, req.(*FirewallInjectScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FirewallAdminService_ServiceDesc is the grpc.ServiceDesc for FirewallAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirewallAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsscience.v1.FirewallAdminService",
	HandlerType: (*FirewallAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FirewallStats",
			Handler:    _FirewallAdminService_FirewallStats_Handler,
		},
		{
			MethodName: "LoadScript",
			Handler:    _FirewallAdminService_LoadScript_Handler,
		},
		{
			MethodName: "RemoveScript",
			Handler:    _FirewallAdminService_RemoveScript_Handler,
		},
		{
			MethodName: "InjectScore",
			Handler:    _FirewallAdminService_InjectScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}

const (
	DSYNCAdminService_SendDSYNCNotify_FullMethodName = "/dnsscience.v1.DSYNCAdminService/SendDSYNCNotify"
)

// DSYNCAdminServiceClient is the client API for DSYNCAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DSYNCAdminService exposes RFC 9859 DSYNC operations over gRPC.
type DSYNCAdminServiceClient interface {
	// SendDSYNCNotify triggers outbound NOTIFY(CDS/CSYNC) to the parent zone.
	// Resolves _dsync.<parent> via live DNS lookup (per D-09). Fire-and-forget (per D-10).
	SendDSYNCNotify(ctx context.Context, in *SendDSYNCNotifyRequest, opts ...grpc.CallOption) (*SendDSYNCNotifyResponse, error)
}

type dSYNCAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDSYNCAdminServiceClient(cc grpc.ClientConnInterface) DSYNCAdminServiceClient {
	return &dSYNCAdminServiceClient{cc}
}

func (c *dSYNCAdminServiceClient) SendDSYNCNotify(ctx context.Context, in *SendDSYNCNotifyRequest, opts ...grpc.CallOption) (*SendDSYNCNotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendDSYNCNotifyResponse)
	err := c.cc.Invoke(ctx, DSYNCAdminService_SendDSYNCNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSYNCAdminServiceServer is the server API for DSYNCAdminService service.
// All implementations must embed UnimplementedDSYNCAdminServiceServer
// for forward compatibility.
//
// DSYNCAdminService exposes RFC 9859 DSYNC operations over gRPC.
type DSYNCAdminServiceServer interface {
	// SendDSYNCNotify triggers outbound NOTIFY(CDS/CSYNC) to the parent zone.
	// Resolves _dsync.<parent> via live DNS lookup (per D-09). Fire-and-forget (per D-10).
	SendDSYNCNotify(context.Context, *SendDSYNCNotifyRequest) (*SendDSYNCNotifyResponse, error)
	mustEmbedUnimplementedDSYNCAdminServiceServer()
}

// UnimplementedDSYNCAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDSYNCAdminServiceServer struct{}

func (UnimplementedDSYNCAdminServiceServer) SendDSYNCNotify(context.Context, *SendDSYNCNotifyRequest) (*SendDSYNCNotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDSYNCNotify not implemented")
}
func (UnimplementedDSYNCAdminServiceServer) mustEmbedUnimplementedDSYNCAdminServiceServer() {}
func (UnimplementedDSYNCAdminServiceServer) testEmbeddedByValue()                           {}

// UnsafeDSYNCAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DSYNCAdminServiceServer will
// result in compilation errors.
type UnsafeDSYNCAdminServiceServer interface {
	mustEmbedUnimplementedDSYNCAdminServiceServer()
}

func RegisterDSYNCAdminServiceServer(s grpc.ServiceRegistrar, srv DSYNCAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedDSYNCAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DSYNCAdminService_ServiceDesc, srv)
}

func _DSYNCAdminService_SendDSYNCNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDSYNCNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSYNCAdminServiceServer).SendDSYNCNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSYNCAdminService_SendDSYNCNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSYNCAdminServiceServer).SendDSYNCNotify(ctx, req.(*SendDSYNCNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DSYNCAdminService_ServiceDesc is the grpc.ServiceDesc for DSYNCAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DSYNCAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsscience.v1.DSYNCAdminService",
	HandlerType: (*DSYNCAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDSYNCNotify",
			Handler:    _DSYNCAdminService_SendDSYNCNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
