// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminFlushCacheRequest_FlushType int32

const (
	AdminFlushCacheRequest_ALL           AdminFlushCacheRequest_FlushType = 0 // Flush entire cache
	AdminFlushCacheRequest_BY_NAME       AdminFlushCacheRequest_FlushType = 1 // Flush specific name
	AdminFlushCacheRequest_BY_DOMAIN     AdminFlushCacheRequest_FlushType = 2 // Flush all under domain
	AdminFlushCacheRequest_BY_TLD        AdminFlushCacheRequest_FlushType = 3 // Flush entire TLD
	AdminFlushCacheRequest_NEGATIVE_ONLY AdminFlushCacheRequest_FlushType = 4 // Flush only negative cache entries
	AdminFlushCacheRequest_EXPIRED_ONLY  AdminFlushCacheRequest_FlushType = 5 // Flush expired entries
)

// Enum value maps for AdminFlushCacheRequest_FlushType.
var (
	AdminFlushCacheRequest_FlushType_name = map[int32]string{
		0: "ALL",
		1: "BY_NAME",
		2: "BY_DOMAIN",
		3: "BY_TLD",
		4: "NEGATIVE_ONLY",
		5: "EXPIRED_ONLY",
	}
	AdminFlushCacheRequest_FlushType_value = map[string]int32{
		"ALL":           0,
		"BY_NAME":       1,
		"BY_DOMAIN":     2,
		"BY_TLD":        3,
		"NEGATIVE_ONLY": 4,
		"EXPIRED_ONLY":  5,
	}
)

func (x AdminFlushCacheRequest_FlushType) Enum() *AdminFlushCacheRequest_FlushType {
	p := new(AdminFlushCacheRequest_FlushType)
	*p = x
	return p
}

func (x AdminFlushCacheRequest_FlushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminFlushCacheRequest_FlushType) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[0].Descriptor()
}

func (AdminFlushCacheRequest_FlushType) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[0]
}

func (x AdminFlushCacheRequest_FlushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminFlushCacheRequest_FlushType.Descriptor instead.
func (AdminFlushCacheRequest_FlushType) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0, 0}
}

type AdminFlushCacheRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Type          AdminFlushCacheRequest_FlushType `protobuf:"varint,1,opt,name=type,proto3,enum=dnsscience.v1.AdminFlushCacheRequest_FlushType" json:"type,omitempty"`
	Name          string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // For BY_NAME, BY_DOMAIN, BY_TLD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFlushCacheRequest) Reset() {
	*x = AdminFlushCacheRequest{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFlushCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFlushCacheRequest) ProtoMessage() {}

func (x *AdminFlushCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFlushCacheRequest.ProtoReflect.Descriptor instead.
func (*AdminFlushCacheRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminFlushCacheRequest) GetType() AdminFlushCacheRequest_FlushType {
	if x != nil {
		return x.Type
	}
	return AdminFlushCacheRequest_ALL
}

func (x *AdminFlushCacheRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AdminFlushCacheResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntriesFlushed uint64                 `protobuf:"varint,1,opt,name=entries_flushed,json=entriesFlushed,proto3" json:"entries_flushed,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminFlushCacheResponse) Reset() {
	*x = AdminFlushCacheResponse{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFlushCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFlushCacheResponse) ProtoMessage() {}

func (x *AdminFlushCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFlushCacheResponse.ProtoReflect.Descriptor instead.
func (*AdminFlushCacheResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminFlushCacheResponse) GetEntriesFlushed() uint64 {
	if x != nil {
		return x.EntriesFlushed
	}
	return 0
}

func (x *AdminFlushCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminCacheStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          uint64                 `protobuf:"varint,1,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses        uint64                 `protobuf:"varint,2,opt,name=misses,proto3" json:"misses,omitempty"`
	Evictions     uint64                 `protobuf:"varint,3,opt,name=evictions,proto3" json:"evictions,omitempty"`
	Expirations   uint64                 `protobuf:"varint,4,opt,name=expirations,proto3" json:"expirations,omitempty"`
	Size          int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	HitRate       float64                `protobuf:"fixed64,6,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,7,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	MaxMemory     int64                  `protobuf:"varint,8,opt,name=max_memory,json=maxMemory,proto3" json:"max_memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCacheStatsResponse) Reset() {
	*x = AdminCacheStatsResponse{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCacheStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCacheStatsResponse) ProtoMessage() {}

func (x *AdminCacheStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCacheStatsResponse.ProtoReflect.Descriptor instead.
func (*AdminCacheStatsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminCacheStatsResponse) GetHits() uint64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *AdminCacheStatsResponse) GetMisses() uint64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *AdminCacheStatsResponse) GetEvictions() uint64 {
	if x != nil {
		return x.Evictions
	}
	return 0
}

func (x *AdminCacheStatsResponse) GetExpirations() uint64 {
	if x != nil {
		return x.Expirations
	}
	return 0
}

func (x *AdminCacheStatsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AdminCacheStatsResponse) GetHitRate() float64 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

func (x *AdminCacheStatsResponse) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *AdminCacheStatsResponse) GetMaxMemory() int64 {
	if x != nil {
		return x.MaxMemory
	}
	return 0
}

type AdminPurgeCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"` // Regex pattern or glob
	Regex         bool                   `protobuf:"varint,2,opt,name=regex,proto3" json:"regex,omitempty"`    // Use regex vs glob
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPurgeCacheRequest) Reset() {
	*x = AdminPurgeCacheRequest{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPurgeCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPurgeCacheRequest) ProtoMessage() {}

func (x *AdminPurgeCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPurgeCacheRequest.ProtoReflect.Descriptor instead.
func (*AdminPurgeCacheRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminPurgeCacheRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *AdminPurgeCacheRequest) GetRegex() bool {
	if x != nil {
		return x.Regex
	}
	return false
}

type AdminPurgeCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntriesPurged uint64                 `protobuf:"varint,1,opt,name=entries_purged,json=entriesPurged,proto3" json:"entries_purged,omitempty"`
	Samples       []string               `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"` // Sample of purged names
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPurgeCacheResponse) Reset() {
	*x = AdminPurgeCacheResponse{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPurgeCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPurgeCacheResponse) ProtoMessage() {}

func (x *AdminPurgeCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPurgeCacheResponse.ProtoReflect.Descriptor instead.
func (*AdminPurgeCacheResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminPurgeCacheResponse) GetEntriesPurged() uint64 {
	if x != nil {
		return x.EntriesPurged
	}
	return 0
}

func (x *AdminPurgeCacheResponse) GetSamples() []string {
	if x != nil {
		return x.Samples
	}
	return nil
}

type AdminRefreshZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneName      string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Force refresh even if not changed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRefreshZoneRequest) Reset() {
	*x = AdminRefreshZoneRequest{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRefreshZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRefreshZoneRequest) ProtoMessage() {}

func (x *AdminRefreshZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRefreshZoneRequest.ProtoReflect.Descriptor instead.
func (*AdminRefreshZoneRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminRefreshZoneRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *AdminRefreshZoneRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type AdminRefreshZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refreshed     bool                   `protobuf:"varint,1,opt,name=refreshed,proto3" json:"refreshed,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RecordsLoaded int32                  `protobuf:"varint,3,opt,name=records_loaded,json=recordsLoaded,proto3" json:"records_loaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRefreshZoneResponse) Reset() {
	*x = AdminRefreshZoneResponse{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRefreshZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRefreshZoneResponse) ProtoMessage() {}

func (x *AdminRefreshZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRefreshZoneResponse.ProtoReflect.Descriptor instead.
func (*AdminRefreshZoneResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminRefreshZoneResponse) GetRefreshed() bool {
	if x != nil {
		return x.Refreshed
	}
	return false
}

func (x *AdminRefreshZoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminRefreshZoneResponse) GetRecordsLoaded() int32 {
	if x != nil {
		return x.RecordsLoaded
	}
	return 0
}

type AdminListZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*AdminZoneInfo       `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListZonesResponse) Reset() {
	*x = AdminListZonesResponse{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListZonesResponse) ProtoMessage() {}

func (x *AdminListZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListZonesResponse.ProtoReflect.Descriptor instead.
func (*AdminListZonesResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminListZonesResponse) GetZones() []*AdminZoneInfo {
	if x != nil {
		return x.Zones
	}
	return nil
}

type AdminZoneInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RecordCount   int32                  `protobuf:"varint,2,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	LastLoaded    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_loaded,json=lastLoaded,proto3" json:"last_loaded,omitempty"`
	SourceFile    string                 `protobuf:"bytes,4,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	Compiled      bool                   `protobuf:"varint,5,opt,name=compiled,proto3" json:"compiled,omitempty"`
	Serial        uint32                 `protobuf:"varint,6,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminZoneInfo) Reset() {
	*x = AdminZoneInfo{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminZoneInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminZoneInfo) ProtoMessage() {}

func (x *AdminZoneInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminZoneInfo.ProtoReflect.Descriptor instead.
func (*AdminZoneInfo) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminZoneInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminZoneInfo) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *AdminZoneInfo) GetLastLoaded() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoaded
	}
	return nil
}

func (x *AdminZoneInfo) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *AdminZoneInfo) GetCompiled() bool {
	if x != nil {
		return x.Compiled
	}
	return false
}

func (x *AdminZoneInfo) GetSerial() uint32 {
	if x != nil {
		return x.Serial
	}
	return 0
}

type AdminReloadZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZonesReloaded int32                  `protobuf:"varint,1,opt,name=zones_reloaded,json=zonesReloaded,proto3" json:"zones_reloaded,omitempty"`
	FailedZones   []string               `protobuf:"bytes,2,rep,name=failed_zones,json=failedZones,proto3" json:"failed_zones,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminReloadZonesResponse) Reset() {
	*x = AdminReloadZonesResponse{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminReloadZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminReloadZonesResponse) ProtoMessage() {}

func (x *AdminReloadZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminReloadZonesResponse.ProtoReflect.Descriptor instead.
func (*AdminReloadZonesResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AdminReloadZonesResponse) GetZonesReloaded() int32 {
	if x != nil {
		return x.ZonesReloaded
	}
	return 0
}

func (x *AdminReloadZonesResponse) GetFailedZones() []string {
	if x != nil {
		return x.FailedZones
	}
	return nil
}

func (x *AdminReloadZonesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminSetQueryLoggingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LogPath       string                 `protobuf:"bytes,2,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"` // Optional: change log path
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`                  // "json" or "text"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSetQueryLoggingRequest) Reset() {
	*x = AdminSetQueryLoggingRequest{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSetQueryLoggingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSetQueryLoggingRequest) ProtoMessage() {}

func (x *AdminSetQueryLoggingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSetQueryLoggingRequest.ProtoReflect.Descriptor instead.
func (*AdminSetQueryLoggingRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AdminSetQueryLoggingRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AdminSetQueryLoggingRequest) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *AdminSetQueryLoggingRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type AdminSetQueryLoggingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSetQueryLoggingResponse) Reset() {
	*x = AdminSetQueryLoggingResponse{}
	mi := &file_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSetQueryLoggingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSetQueryLoggingResponse) ProtoMessage() {}

func (x *AdminSetQueryLoggingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSetQueryLoggingResponse.ProtoReflect.Descriptor instead.
func (*AdminSetQueryLoggingResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AdminSetQueryLoggingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminSetQueryLoggingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminQueryLoggingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LogPath       string                 `protobuf:"bytes,2,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	QueriesLogged int64                  `protobuf:"varint,4,opt,name=queries_logged,json=queriesLogged,proto3" json:"queries_logged,omitempty"`
	LogSizeBytes  int64                  `protobuf:"varint,5,opt,name=log_size_bytes,json=logSizeBytes,proto3" json:"log_size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminQueryLoggingStatusResponse) Reset() {
	*x = AdminQueryLoggingStatusResponse{}
	mi := &file_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminQueryLoggingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminQueryLoggingStatusResponse) ProtoMessage() {}

func (x *AdminQueryLoggingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminQueryLoggingStatusResponse.ProtoReflect.Descriptor instead.
func (*AdminQueryLoggingStatusResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{12}
}

func (x *AdminQueryLoggingStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AdminQueryLoggingStatusResponse) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *AdminQueryLoggingStatusResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AdminQueryLoggingStatusResponse) GetQueriesLogged() int64 {
	if x != nil {
		return x.QueriesLogged
	}
	return 0
}

func (x *AdminQueryLoggingStatusResponse) GetLogSizeBytes() int64 {
	if x != nil {
		return x.LogSizeBytes
	}
	return 0
}

type AdminSetRateLimitRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enabled            bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ResponsesPerSecond int32                  `protobuf:"varint,2,opt,name=responses_per_second,json=responsesPerSecond,proto3" json:"responses_per_second,omitempty"`
	ErrorsPerSecond    int32                  `protobuf:"varint,3,opt,name=errors_per_second,json=errorsPerSecond,proto3" json:"errors_per_second,omitempty"`
	NxdomainsPerSecond int32                  `protobuf:"varint,4,opt,name=nxdomains_per_second,json=nxdomainsPerSecond,proto3" json:"nxdomains_per_second,omitempty"`
	ExemptClients      []string               `protobuf:"bytes,5,rep,name=exempt_clients,json=exemptClients,proto3" json:"exempt_clients,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdminSetRateLimitRequest) Reset() {
	*x = AdminSetRateLimitRequest{}
	mi := &file_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSetRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSetRateLimitRequest) ProtoMessage() {}

func (x *AdminSetRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSetRateLimitRequest.ProtoReflect.Descriptor instead.
func (*AdminSetRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminSetRateLimitRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AdminSetRateLimitRequest) GetResponsesPerSecond() int32 {
	if x != nil {
		return x.ResponsesPerSecond
	}
	return 0
}

func (x *AdminSetRateLimitRequest) GetErrorsPerSecond() int32 {
	if x != nil {
		return x.ErrorsPerSecond
	}
	return 0
}

func (x *AdminSetRateLimitRequest) GetNxdomainsPerSecond() int32 {
	if x != nil {
		return x.NxdomainsPerSecond
	}
	return 0
}

func (x *AdminSetRateLimitRequest) GetExemptClients() []string {
	if x != nil {
		return x.ExemptClients
	}
	return nil
}

type AdminSetRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSetRateLimitResponse) Reset() {
	*x = AdminSetRateLimitResponse{}
	mi := &file_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSetRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSetRateLimitResponse) ProtoMessage() {}

func (x *AdminSetRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSetRateLimitResponse.ProtoReflect.Descriptor instead.
func (*AdminSetRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AdminSetRateLimitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminSetRateLimitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminRateLimitStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enabled            bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ResponsesPerSecond int32                  `protobuf:"varint,2,opt,name=responses_per_second,json=responsesPerSecond,proto3" json:"responses_per_second,omitempty"`
	ErrorsPerSecond    int32                  `protobuf:"varint,3,opt,name=errors_per_second,json=errorsPerSecond,proto3" json:"errors_per_second,omitempty"`
	NxdomainsPerSecond int32                  `protobuf:"varint,4,opt,name=nxdomains_per_second,json=nxdomainsPerSecond,proto3" json:"nxdomains_per_second,omitempty"`
	TotalDropped       uint64                 `protobuf:"varint,5,opt,name=total_dropped,json=totalDropped,proto3" json:"total_dropped,omitempty"`
	TotalSlipped       uint64                 `protobuf:"varint,6,opt,name=total_slipped,json=totalSlipped,proto3" json:"total_slipped,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdminRateLimitStatusResponse) Reset() {
	*x = AdminRateLimitStatusResponse{}
	mi := &file_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRateLimitStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRateLimitStatusResponse) ProtoMessage() {}

func (x *AdminRateLimitStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRateLimitStatusResponse.ProtoReflect.Descriptor instead.
func (*AdminRateLimitStatusResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AdminRateLimitStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AdminRateLimitStatusResponse) GetResponsesPerSecond() int32 {
	if x != nil {
		return x.ResponsesPerSecond
	}
	return 0
}

func (x *AdminRateLimitStatusResponse) GetErrorsPerSecond() int32 {
	if x != nil {
		return x.ErrorsPerSecond
	}
	return 0
}

func (x *AdminRateLimitStatusResponse) GetNxdomainsPerSecond() int32 {
	if x != nil {
		return x.NxdomainsPerSecond
	}
	return 0
}

func (x *AdminRateLimitStatusResponse) GetTotalDropped() uint64 {
	if x != nil {
		return x.TotalDropped
	}
	return 0
}

func (x *AdminRateLimitStatusResponse) GetTotalSlipped() uint64 {
	if x != nil {
		return x.TotalSlipped
	}
	return 0
}

type AdminServerStatusResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Version       string                  `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	StartTime     *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	UptimeSeconds int64                   `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Goroutines    int32                   `protobuf:"varint,4,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	MemoryBytes   int64                   `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	ZonesLoaded   int32                   `protobuf:"varint,6,opt,name=zones_loaded,json=zonesLoaded,proto3" json:"zones_loaded,omitempty"`
	Healthy       bool                    `protobuf:"varint,7,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Components    []*AdminComponentStatus `protobuf:"bytes,8,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminServerStatusResponse) Reset() {
	*x = AdminServerStatusResponse{}
	mi := &file_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminServerStatusResponse) ProtoMessage() {}

func (x *AdminServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminServerStatusResponse.ProtoReflect.Descriptor instead.
func (*AdminServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AdminServerStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AdminServerStatusResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AdminServerStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *AdminServerStatusResponse) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *AdminServerStatusResponse) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *AdminServerStatusResponse) GetZonesLoaded() int32 {
	if x != nil {
		return x.ZonesLoaded
	}
	return 0
}

func (x *AdminServerStatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *AdminServerStatusResponse) GetComponents() []*AdminComponentStatus {
	if x != nil {
		return x.Components
	}
	return nil
}

type AdminComponentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminComponentStatus) Reset() {
	*x = AdminComponentStatus{}
	mi := &file_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminComponentStatus) ProtoMessage() {}

func (x *AdminComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminComponentStatus.ProtoReflect.Descriptor instead.
func (*AdminComponentStatus) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{17}
}

func (x *AdminComponentStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminComponentStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *AdminComponentStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminMetricsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QueriesTotal     uint64                 `protobuf:"varint,1,opt,name=queries_total,json=queriesTotal,proto3" json:"queries_total,omitempty"`
	QueriesUdp       uint64                 `protobuf:"varint,2,opt,name=queries_udp,json=queriesUdp,proto3" json:"queries_udp,omitempty"`
	QueriesTcp       uint64                 `protobuf:"varint,3,opt,name=queries_tcp,json=queriesTcp,proto3" json:"queries_tcp,omitempty"`
	CacheHits        uint64                 `protobuf:"varint,4,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	CacheMisses      uint64                 `protobuf:"varint,5,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	UpstreamFailures uint64                 `protobuf:"varint,6,opt,name=upstream_failures,json=upstreamFailures,proto3" json:"upstream_failures,omitempty"`
	AvgLatencyMs     float64                `protobuf:"fixed64,7,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P99LatencyMs     float64                `protobuf:"fixed64,8,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminMetricsResponse) Reset() {
	*x = AdminMetricsResponse{}
	mi := &file_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMetricsResponse) ProtoMessage() {}

func (x *AdminMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMetricsResponse.ProtoReflect.Descriptor instead.
func (*AdminMetricsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{18}
}

func (x *AdminMetricsResponse) GetQueriesTotal() uint64 {
	if x != nil {
		return x.QueriesTotal
	}
	return 0
}

func (x *AdminMetricsResponse) GetQueriesUdp() uint64 {
	if x != nil {
		return x.QueriesUdp
	}
	return 0
}

func (x *AdminMetricsResponse) GetQueriesTcp() uint64 {
	if x != nil {
		return x.QueriesTcp
	}
	return 0
}

func (x *AdminMetricsResponse) GetCacheHits() uint64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *AdminMetricsResponse) GetCacheMisses() uint64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *AdminMetricsResponse) GetUpstreamFailures() uint64 {
	if x != nil {
		return x.UpstreamFailures
	}
	return 0
}

func (x *AdminMetricsResponse) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *AdminMetricsResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

type AdminShutdownRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GracePeriodSeconds int32                  `protobuf:"varint,1,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"` // Graceful shutdown period
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdminShutdownRequest) Reset() {
	*x = AdminShutdownRequest{}
	mi := &file_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminShutdownRequest) ProtoMessage() {}

func (x *AdminShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminShutdownRequest.ProtoReflect.Descriptor instead.
func (*AdminShutdownRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{19}
}

func (x *AdminShutdownRequest) GetGracePeriodSeconds() int32 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

type AdminShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminShutdownResponse) Reset() {
	*x = AdminShutdownResponse{}
	mi := &file_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminShutdownResponse) ProtoMessage() {}

func (x *AdminShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminShutdownResponse.ProtoReflect.Descriptor instead.
func (*AdminShutdownResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{20}
}

func (x *AdminShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminListConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // "tcp", "udp", or "" for all
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`      // Max connections to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListConnectionsRequest) Reset() {
	*x = AdminListConnectionsRequest{}
	mi := &file_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListConnectionsRequest) ProtoMessage() {}

func (x *AdminListConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListConnectionsRequest.ProtoReflect.Descriptor instead.
func (*AdminListConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{21}
}

func (x *AdminListConnectionsRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AdminListConnectionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AdminListConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*AdminConnectionInfo `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListConnectionsResponse) Reset() {
	*x = AdminListConnectionsResponse{}
	mi := &file_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListConnectionsResponse) ProtoMessage() {}

func (x *AdminListConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListConnectionsResponse.ProtoReflect.Descriptor instead.
func (*AdminListConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{22}
}

func (x *AdminListConnectionsResponse) GetConnections() []*AdminConnectionInfo {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *AdminListConnectionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AdminConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientPort    int32                  `protobuf:"varint,4,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	QueriesServed int64                  `protobuf:"varint,6,opt,name=queries_served,json=queriesServed,proto3" json:"queries_served,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminConnectionInfo) Reset() {
	*x = AdminConnectionInfo{}
	mi := &file_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminConnectionInfo) ProtoMessage() {}

func (x *AdminConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminConnectionInfo.ProtoReflect.Descriptor instead.
func (*AdminConnectionInfo) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{23}
}

func (x *AdminConnectionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminConnectionInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AdminConnectionInfo) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AdminConnectionInfo) GetClientPort() int32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *AdminConnectionInfo) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *AdminConnectionInfo) GetQueriesServed() int64 {
	if x != nil {
		return x.QueriesServed
	}
	return 0
}

type AdminKillConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminKillConnectionRequest) Reset() {
	*x = AdminKillConnectionRequest{}
	mi := &file_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminKillConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminKillConnectionRequest) ProtoMessage() {}

func (x *AdminKillConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminKillConnectionRequest.ProtoReflect.Descriptor instead.
func (*AdminKillConnectionRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{24}
}

func (x *AdminKillConnectionRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type AdminKillConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminKillConnectionResponse) Reset() {
	*x = AdminKillConnectionResponse{}
	mi := &file_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminKillConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminKillConnectionResponse) ProtoMessage() {}

func (x *AdminKillConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminKillConnectionResponse.ProtoReflect.Descriptor instead.
func (*AdminKillConnectionResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{25}
}

func (x *AdminKillConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminKillConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\rdnsscience.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\x16AdminFlushCacheRequest\x12C\n" +
	"\x04type\x18\x01 \x01(\x0e2/.dnsscience.v1.AdminFlushCacheRequest.FlushTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"a\n" +
	"\tFlushType\x12\a\n" +
	"\x03ALL\x10\x00\x12\v\n" +
	"\aBY_NAME\x10\x01\x12\r\n" +
	"\tBY_DOMAIN\x10\x02\x12\n" +
	"\n" +
	"\x06BY_TLD\x10\x03\x12\x11\n" +
	"\rNEGATIVE_ONLY\x10\x04\x12\x10\n" +
	"\fEXPIRED_ONLY\x10\x05\"\\\n" +
	"\x17AdminFlushCacheResponse\x12'\n" +
	"\x0fentries_flushed\x18\x01 \x01(\x04R\x0eentriesFlushed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf6\x01\n" +
	"\x17AdminCacheStatsResponse\x12\x12\n" +
	"\x04hits\x18\x01 \x01(\x04R\x04hits\x12\x16\n" +
	"\x06misses\x18\x02 \x01(\x04R\x06misses\x12\x1c\n" +
	"\tevictions\x18\x03 \x01(\x04R\tevictions\x12 \n" +
	"\vexpirations\x18\x04 \x01(\x04R\vexpirations\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\x12\x19\n" +
	"\bhit_rate\x18\x06 \x01(\x01R\ahitRate\x12!\n" +
	"\fmemory_bytes\x18\a \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"max_memory\x18\b \x01(\x03R\tmaxMemory\"H\n" +
	"\x16AdminPurgeCacheRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x14\n" +
	"\x05regex\x18\x02 \x01(\bR\x05regex\"Z\n" +
	"\x17AdminPurgeCacheResponse\x12%\n" +
	"\x0eentries_purged\x18\x01 \x01(\x04R\rentriesPurged\x12\x18\n" +
	"\asamples\x18\x02 \x03(\tR\asamples\"L\n" +
	"\x17AdminRefreshZoneRequest\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"y\n" +
	"\x18AdminRefreshZoneResponse\x12\x1c\n" +
	"\trefreshed\x18\x01 \x01(\bR\trefreshed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0erecords_loaded\x18\x03 \x01(\x05R\rrecordsLoaded\"L\n" +
	"\x16AdminListZonesResponse\x122\n" +
	"\x05zones\x18\x01 \x03(\v2\x1c.dnsscience.v1.AdminZoneInfoR\x05zones\"\xd8\x01\n" +
	"\rAdminZoneInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\frecord_count\x18\x02 \x01(\x05R\vrecordCount\x12;\n" +
	"\vlast_loaded\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastLoaded\x12\x1f\n" +
	"\vsource_file\x18\x04 \x01(\tR\n" +
	"sourceFile\x12\x1a\n" +
	"\bcompiled\x18\x05 \x01(\bR\bcompiled\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\rR\x06serial\"~\n" +
	"\x18AdminReloadZonesResponse\x12%\n" +
	"\x0ezones_reloaded\x18\x01 \x01(\x05R\rzonesReloaded\x12!\n" +
	"\ffailed_zones\x18\x02 \x03(\tR\vfailedZones\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"j\n" +
	"\x1bAdminSetQueryLoggingRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x19\n" +
	"\blog_path\x18\x02 \x01(\tR\alogPath\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"R\n" +
	"\x1cAdminSetQueryLoggingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x01\n" +
	"\x1fAdminQueryLoggingStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x19\n" +
	"\blog_path\x18\x02 \x01(\tR\alogPath\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12%\n" +
	"\x0equeries_logged\x18\x04 \x01(\x03R\rqueriesLogged\x12$\n" +
	"\x0elog_size_bytes\x18\x05 \x01(\x03R\flogSizeBytes\"\xeb\x01\n" +
	"\x18AdminSetRateLimitRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x120\n" +
	"\x14responses_per_second\x18\x02 \x01(\x05R\x12responsesPerSecond\x12*\n" +
	"\x11errors_per_second\x18\x03 \x01(\x05R\x0ferrorsPerSecond\x120\n" +
	"\x14nxdomains_per_second\x18\x04 \x01(\x05R\x12nxdomainsPerSecond\x12%\n" +
	"\x0eexempt_clients\x18\x05 \x03(\tR\rexemptClients\"O\n" +
	"\x19AdminSetRateLimitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x92\x02\n" +
	"\x1cAdminRateLimitStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x120\n" +
	"\x14responses_per_second\x18\x02 \x01(\x05R\x12responsesPerSecond\x12*\n" +
	"\x11errors_per_second\x18\x03 \x01(\x05R\x0ferrorsPerSecond\x120\n" +
	"\x14nxdomains_per_second\x18\x04 \x01(\x05R\x12nxdomainsPerSecond\x12#\n" +
	"\rtotal_dropped\x18\x05 \x01(\x04R\ftotalDropped\x12#\n" +
	"\rtotal_slipped\x18\x06 \x01(\x04R\ftotalSlipped\"\xdc\x02\n" +
	"\x19AdminServerStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x04 \x01(\x05R\n" +
	"goroutines\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x12!\n" +
	"\fzones_loaded\x18\x06 \x01(\x05R\vzonesLoaded\x12\x18\n" +
	"\ahealthy\x18\a \x01(\bR\ahealthy\x12C\n" +
	"\n" +
	"components\x18\b \x03(\v2#.dnsscience.v1.AdminComponentStatusR\n" +
	"components\"^\n" +
	"\x14AdminComponentStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb8\x02\n" +
	"\x14AdminMetricsResponse\x12#\n" +
	"\rqueries_total\x18\x01 \x01(\x04R\fqueriesTotal\x12\x1f\n" +
	"\vqueries_udp\x18\x02 \x01(\x04R\n" +
	"queriesUdp\x12\x1f\n" +
	"\vqueries_tcp\x18\x03 \x01(\x04R\n" +
	"queriesTcp\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x04 \x01(\x04R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\x05 \x01(\x04R\vcacheMisses\x12+\n" +
	"\x11upstream_failures\x18\x06 \x01(\x04R\x10upstreamFailures\x12$\n" +
	"\x0eavg_latency_ms\x18\a \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\b \x01(\x01R\fp99LatencyMs\"H\n" +
	"\x14AdminShutdownRequest\x120\n" +
	"\x14grace_period_seconds\x18\x01 \x01(\x05R\x12gracePeriodSeconds\"K\n" +
	"\x15AdminShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x1bAdminListConnectionsRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x85\x01\n" +
	"\x1cAdminListConnectionsResponse\x12D\n" +
	"\vconnections\x18\x01 \x03(\v2\".dnsscience.v1.AdminConnectionInfoR\vconnections\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xe5\x01\n" +
	"\x13AdminConnectionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vclient_port\x18\x04 \x01(\x05R\n" +
	"clientPort\x12=\n" +
	"\fconnected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12%\n" +
	"\x0equeries_served\x18\x06 \x01(\x03R\rqueriesServed\"A\n" +
	"\x1aAdminKillConnectionRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"Q\n" +
	"\x1bAdminKillConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf2\n" +
	"\n" +
	"\fAdminService\x12[\n" +
	"\n" +
	"FlushCache\x12%.dnsscience.v1.AdminFlushCacheRequest\x1a&.dnsscience.v1.AdminFlushCacheResponse\x12O\n" +
	"\rGetCacheStats\x12\x16.google.protobuf.Empty\x1a&.dnsscience.v1.AdminCacheStatsResponse\x12[\n" +
	"\n" +
	"PurgeCache\x12%.dnsscience.v1.AdminPurgeCacheRequest\x1a&.dnsscience.v1.AdminPurgeCacheResponse\x12^\n" +
	"\vRefreshZone\x12&.dnsscience.v1.AdminRefreshZoneRequest\x1a'.dnsscience.v1.AdminRefreshZoneResponse\x12J\n" +
	"\tListZones\x12\x16.google.protobuf.Empty\x1a%.dnsscience.v1.AdminListZonesResponse\x12N\n" +
	"\vReloadZones\x12\x16.google.protobuf.Empty\x1a'.dnsscience.v1.AdminReloadZonesResponse\x12j\n" +
	"\x0fSetQueryLogging\x12*.dnsscience.v1.AdminSetQueryLoggingRequest\x1a+.dnsscience.v1.AdminSetQueryLoggingResponse\x12_\n" +
	"\x15GetQueryLoggingStatus\x12\x16.google.protobuf.Empty\x1a..dnsscience.v1.AdminQueryLoggingStatusResponse\x12a\n" +
	"\fSetRateLimit\x12'.dnsscience.v1.AdminSetRateLimitRequest\x1a(.dnsscience.v1.AdminSetRateLimitResponse\x12Y\n" +
	"\x12GetRateLimitStatus\x12\x16.google.protobuf.Empty\x1a+.dnsscience.v1.AdminRateLimitStatusResponse\x12S\n" +
	"\x0fGetServerStatus\x12\x16.google.protobuf.Empty\x1a(.dnsscience.v1.AdminServerStatusResponse\x12I\n" +
	"\n" +
	"GetMetrics\x12\x16.google.protobuf.Empty\x1a#.dnsscience.v1.AdminMetricsResponse\x12[\n" +
	"\x0eShutdownServer\x12#.dnsscience.v1.AdminShutdownRequest\x1a$.dnsscience.v1.AdminShutdownResponse\x12j\n" +
	"\x0fListConnections\x12*.dnsscience.v1.AdminListConnectionsRequest\x1a+.dnsscience.v1.AdminListConnectionsResponse\x12g\n" +
	"\x0eKillConnection\x12).dnsscience.v1.AdminKillConnectionRequest\x1a*.dnsscience.v1.AdminKillConnectionResponseB5Z3github.com/dnsscience/dnsscienced/api/grpc/proto/pbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_admin_proto_goTypes = []any{
	(AdminFlushCacheRequest_FlushType)(0),   // 0: dnsscience.v1.AdminFlushCacheRequest.FlushType
	(*AdminFlushCacheRequest)(nil),          // 1: dnsscience.v1.AdminFlushCacheRequest
	(*AdminFlushCacheResponse)(nil),         // 2: dnsscience.v1.AdminFlushCacheResponse
	(*AdminCacheStatsResponse)(nil),         // 3: dnsscience.v1.AdminCacheStatsResponse
	(*AdminPurgeCacheRequest)(nil),          // 4: dnsscience.v1.AdminPurgeCacheRequest
	(*AdminPurgeCacheResponse)(nil),         // 5: dnsscience.v1.AdminPurgeCacheResponse
	(*AdminRefreshZoneRequest)(nil),         // 6: dnsscience.v1.AdminRefreshZoneRequest
	(*AdminRefreshZoneResponse)(nil),        // 7: dnsscience.v1.AdminRefreshZoneResponse
	(*AdminListZonesResponse)(nil),          // 8: dnsscience.v1.AdminListZonesResponse
	(*AdminZoneInfo)(nil),                   // 9: dnsscience.v1.AdminZoneInfo
	(*AdminReloadZonesResponse)(nil),        // 10: dnsscience.v1.AdminReloadZonesResponse
	(*AdminSetQueryLoggingRequest)(nil),     // 11: dnsscience.v1.AdminSetQueryLoggingRequest
	(*AdminSetQueryLoggingResponse)(nil),    // 12: dnsscience.v1.AdminSetQueryLoggingResponse
	(*AdminQueryLoggingStatusResponse)(nil), // 13: dnsscience.v1.AdminQueryLoggingStatusResponse
	(*AdminSetRateLimitRequest)(nil),        // 14: dnsscience.v1.AdminSetRateLimitRequest
	(*AdminSetRateLimitResponse)(nil),       // 15: dnsscience.v1.AdminSetRateLimitResponse
	(*AdminRateLimitStatusResponse)(nil),    // 16: dnsscience.v1.AdminRateLimitStatusResponse
	(*AdminServerStatusResponse)(nil),       // 17: dnsscience.v1.AdminServerStatusResponse
	(*AdminComponentStatus)(nil),            // 18: dnsscience.v1.AdminComponentStatus
	(*AdminMetricsResponse)(nil),            // 19: dnsscience.v1.AdminMetricsResponse
	(*AdminShutdownRequest)(nil),            // 20: dnsscience.v1.AdminShutdownRequest
	(*AdminShutdownResponse)(nil),           // 21: dnsscience.v1.AdminShutdownResponse
	(*AdminListConnectionsRequest)(nil),     // 22: dnsscience.v1.AdminListConnectionsRequest
	(*AdminListConnectionsResponse)(nil),    // 23: dnsscience.v1.AdminListConnectionsResponse
	(*AdminConnectionInfo)(nil),             // 24: dnsscience.v1.AdminConnectionInfo
	(*AdminKillConnectionRequest)(nil),      // 25: dnsscience.v1.AdminKillConnectionRequest
	(*AdminKillConnectionResponse)(nil),     // 26: dnsscience.v1.AdminKillConnectionResponse
	(*timestamppb.Timestamp)(nil),           // 27: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 28: google.protobuf.Empty
}
var file_admin_proto_depIdxs = []int32{
	0,  // 0: dnsscience.v1.AdminFlushCacheRequest.type:type_name -> dnsscience.v1.AdminFlushCacheRequest.FlushType
	9,  // 1: dnsscience.v1.AdminListZonesResponse.zones:type_name -> dnsscience.v1.AdminZoneInfo
	27, // 2: dnsscience.v1.AdminZoneInfo.last_loaded:type_name -> google.protobuf.Timestamp
	27, // 3: dnsscience.v1.AdminServerStatusResponse.start_time:type_name -> google.protobuf.Timestamp
	18, // 4: dnsscience.v1.AdminServerStatusResponse.components:type_name -> dnsscience.v1.AdminComponentStatus
	24, // 5: dnsscience.v1.AdminListConnectionsResponse.connections:type_name -> dnsscience.v1.AdminConnectionInfo
	27, // 6: dnsscience.v1.AdminConnectionInfo.connected_at:type_name -> google.protobuf.Timestamp
	1,  // 7: dnsscience.v1.AdminService.FlushCache:input_type -> dnsscience.v1.AdminFlushCacheRequest
	28, // 8: dnsscience.v1.AdminService.GetCacheStats:input_type -> google.protobuf.Empty
	4,  // 9: dnsscience.v1.AdminService.PurgeCache:input_type -> dnsscience.v1.AdminPurgeCacheRequest
	6,  // 10: dnsscience.v1.AdminService.RefreshZone:input_type -> dnsscience.v1.AdminRefreshZoneRequest
	28, // 11: dnsscience.v1.AdminService.ListZones:input_type -> google.protobuf.Empty
	28, // 12: dnsscience.v1.AdminService.ReloadZones:input_type -> google.protobuf.Empty
	11, // 13: dnsscience.v1.AdminService.SetQueryLogging:input_type -> dnsscience.v1.AdminSetQueryLoggingRequest
	28, // 14: dnsscience.v1.AdminService.GetQueryLoggingStatus:input_type -> google.protobuf.Empty
	14, // 15: dnsscience.v1.AdminService.SetRateLimit:input_type -> dnsscience.v1.AdminSetRateLimitRequest
	28, // 16: dnsscience.v1.AdminService.GetRateLimitStatus:input_type -> google.protobuf.Empty
	28, // 17: dnsscience.v1.AdminService.GetServerStatus:input_type -> google.protobuf.Empty
	28, // 18: dnsscience.v1.AdminService.GetMetrics:input_type -> google.protobuf.Empty
	20, // 19: dnsscience.v1.AdminService.ShutdownServer:input_type -> dnsscience.v1.AdminShutdownRequest
	22, // 20: dnsscience.v1.AdminService.ListConnections:input_type -> dnsscience.v1.AdminListConnectionsRequest
	25, // 21: dnsscience.v1.AdminService.KillConnection:input_type -> dnsscience.v1.AdminKillConnectionRequest
	2,  // 22: dnsscience.v1.AdminService.FlushCache:output_type -> dnsscience.v1.AdminFlushCacheResponse
	3,  // 23: dnsscience.v1.AdminService.GetCacheStats:output_type -> dnsscience.v1.AdminCacheStatsResponse
	5,  // 24: dnsscience.v1.AdminService.PurgeCache:output_type -> dnsscience.v1.AdminPurgeCacheResponse
	7,  // 25: dnsscience.v1.AdminService.RefreshZone:output_type -> dnsscience.v1.AdminRefreshZoneResponse
	8,  // 26: dnsscience.v1.AdminService.ListZones:output_type -> dnsscience.v1.AdminListZonesResponse
	10, // 27: dnsscience.v1.AdminService.ReloadZones:output_type -> dnsscience.v1.AdminReloadZonesResponse
	12, // 28: dnsscience.v1.AdminService.SetQueryLogging:output_type -> dnsscience.v1.AdminSetQueryLoggingResponse
	13, // 29: dnsscience.v1.AdminService.GetQueryLoggingStatus:output_type -> dnsscience.v1.AdminQueryLoggingStatusResponse
	15, // 30: dnsscience.v1.AdminService.SetRateLimit:output_type -> dnsscience.v1.AdminSetRateLimitResponse
	16, // 31: dnsscience.v1.AdminService.GetRateLimitStatus:output_type -> dnsscience.v1.AdminRateLimitStatusResponse
	17, // 32: dnsscience.v1.AdminService.GetServerStatus:output_type -> dnsscience.v1.AdminServerStatusResponse
	19, // 33: dnsscience.v1.AdminService.GetMetrics:output_type -> dnsscience.v1.AdminMetricsResponse
	21, // 34: dnsscience.v1.AdminService.ShutdownServer:output_type -> dnsscience.v1.AdminShutdownResponse
	23, // 35: dnsscience.v1.AdminService.ListConnections:output_type -> dnsscience.v1.AdminListConnectionsResponse
	26, // 36: dnsscience.v1.AdminService.KillConnection:output_type -> dnsscience.v1.AdminKillConnectionResponse
	22, // [22:37] is the sub-list for method output_type
	7,  // [7:22] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		EnumInfos:         file_admin_proto_enumTypes,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
