// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: views.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ViewService_ListViews_FullMethodName          = "/dnsscience.v1.ViewService/ListViews"
	ViewService_GetView_FullMethodName            = "/dnsscience.v1.ViewService/GetView"
	ViewService_CreateView_FullMethodName         = "/dnsscience.v1.ViewService/CreateView"
	ViewService_UpdateView_FullMethodName         = "/dnsscience.v1.ViewService/UpdateView"
	ViewService_DeleteView_FullMethodName         = "/dnsscience.v1.ViewService/DeleteView"
	ViewService_MatchClientToView_FullMethodName  = "/dnsscience.v1.ViewService/MatchClientToView"
	ViewService_AttachZoneToView_FullMethodName   = "/dnsscience.v1.ViewService/AttachZoneToView"
	ViewService_DetachZoneFromView_FullMethodName = "/dnsscience.v1.ViewService/DetachZoneFromView"
)

// ViewServiceClient is the client API for ViewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ViewService manages DNS views (split-horizon DNS)
// Views allow different DNS responses based on query source
type ViewServiceClient interface {
	// ListViews returns all configured views
	ListViews(ctx context.Context, in *ListViewsRequest, opts ...grpc.CallOption) (*ListViewsResponse, error)
	// GetView returns details about a specific view
	GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*GetViewResponse, error)
	// CreateView creates a new view
	CreateView(ctx context.Context, in *CreateViewRequest, opts ...grpc.CallOption) (*CreateViewResponse, error)
	// UpdateView updates view configuration
	UpdateView(ctx context.Context, in *UpdateViewRequest, opts ...grpc.CallOption) (*UpdateViewResponse, error)
	// DeleteView deletes a view
	DeleteView(ctx context.Context, in *DeleteViewRequest, opts ...grpc.CallOption) (*DeleteViewResponse, error)
	// MatchClientToView determines which view matches a client
	MatchClientToView(ctx context.Context, in *MatchClientRequest, opts ...grpc.CallOption) (*MatchClientResponse, error)
	// AttachZoneToView attaches a zone to a view
	AttachZoneToView(ctx context.Context, in *AttachZoneRequest, opts ...grpc.CallOption) (*AttachZoneResponse, error)
	// DetachZoneFromView removes zone from a view
	DetachZoneFromView(ctx context.Context, in *DetachZoneRequest, opts ...grpc.CallOption) (*DetachZoneResponse, error)
}

type viewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewViewServiceClient(cc grpc.ClientConnInterface) ViewServiceClient {
	return &viewServiceClient{cc}
}

func (c *viewServiceClient) ListViews(ctx context.Context, in *ListViewsRequest, opts ...grpc.CallOption) (*ListViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListViewsResponse)
	err := c.cc.Invoke(ctx, ViewService_ListViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewServiceClient) GetView(ctx context.Context, in *GetViewRequest, opts ...grpc.CallOption) (*GetViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetViewResponse)
	err := c.cc.Invoke(ctx, ViewService_GetView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewServiceClient) CreateView(ctx context.Context, in *CreateViewRequest, opts ...grpc.CallOption) (*CreateViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateViewResponse)
	err := c.cc.Invoke(ctx, ViewService_CreateView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewServiceClient) UpdateView(ctx context.Context, in *UpdateViewRequest, opts ...grpc.CallOption) (*UpdateViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateViewResponse)
	err := c.cc.Invoke(ctx, ViewService_UpdateView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewServiceClient) DeleteView(ctx context.Context, in *DeleteViewRequest, opts ...grpc.CallOption) (*DeleteViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteViewResponse)
	err := c.cc.Invoke(ctx, ViewService_DeleteView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewServiceClient) MatchClientToView(ctx context.Context, in *MatchClientRequest, opts ...grpc.CallOption) (*MatchClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchClientResponse)
	err := c.cc.Invoke(ctx, ViewService_MatchClientToView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewServiceClient) AttachZoneToView(ctx context.Context, in *AttachZoneRequest, opts ...grpc.CallOption) (*AttachZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachZoneResponse)
	err := c.cc.Invoke(ctx, ViewService_AttachZoneToView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewServiceClient) DetachZoneFromView(ctx context.Context, in *DetachZoneRequest, opts ...grpc.CallOption) (*DetachZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachZoneResponse)
	err := c.cc.Invoke(ctx, ViewService_DetachZoneFromView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViewServiceServer is the server API for ViewService service.
// All implementations must embed UnimplementedViewServiceServer
// for forward compatibility.
//
// ViewService manages DNS views (split-horizon DNS)
// Views allow different DNS responses based on query source
type ViewServiceServer interface {
	// ListViews returns all configured views
	ListViews(context.Context, *ListViewsRequest) (*ListViewsResponse, error)
	// GetView returns details about a specific view
	GetView(context.Context, *GetViewRequest) (*GetViewResponse, error)
	// CreateView creates a new view
	CreateView(context.Context, *CreateViewRequest) (*CreateViewResponse, error)
	// UpdateView updates view configuration
	UpdateView(context.Context, *UpdateViewRequest) (*UpdateViewResponse, error)
	// DeleteView deletes a view
	DeleteView(context.Context, *DeleteViewRequest) (*DeleteViewResponse, error)
	// MatchClientToView determines which view matches a client
	MatchClientToView(context.Context, *MatchClientRequest) (*MatchClientResponse, error)
	// AttachZoneToView attaches a zone to a view
	AttachZoneToView(context.Context, *AttachZoneRequest) (*AttachZoneResponse, error)
	// DetachZoneFromView removes zone from a view
	DetachZoneFromView(context.Context, *DetachZoneRequest) (*DetachZoneResponse, error)
	mustEmbedUnimplementedViewServiceServer()
}

// UnimplementedViewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedViewServiceServer struct{}

func (UnimplementedViewServiceServer) ListViews(context.Context, *ListViewsRequest) (*ListViewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListViews not implemented")
}
func (UnimplementedViewServiceServer) GetView(context.Context, *GetViewRequest) (*GetViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetView not implemented")
}
func (UnimplementedViewServiceServer) CreateView(context.Context, *CreateViewRequest) (*CreateViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateView not implemented")
}
func (UnimplementedViewServiceServer) UpdateView(context.Context, *UpdateViewRequest) (*UpdateViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateView not implemented")
}
func (UnimplementedViewServiceServer) DeleteView(context.Context, *DeleteViewRequest) (*DeleteViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteView not implemented")
}
func (UnimplementedViewServiceServer) MatchClientToView(context.Context, *MatchClientRequest) (*MatchClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchClientToView not implemented")
}
func (UnimplementedViewServiceServer) AttachZoneToView(context.Context, *AttachZoneRequest) (*AttachZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachZoneToView not implemented")
}
func (UnimplementedViewServiceServer) DetachZoneFromView(context.Context, *DetachZoneRequest) (*DetachZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachZoneFromView not implemented")
}
func (UnimplementedViewServiceServer) mustEmbedUnimplementedViewServiceServer() {}
func (UnimplementedViewServiceServer) testEmbeddedByValue()                     {}

// UnsafeViewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ViewServiceServer will
// result in compilation errors.
type UnsafeViewServiceServer interface {
	mustEmbedUnimplementedViewServiceServer()
}

func RegisterViewServiceServer(s grpc.ServiceRegistrar, srv ViewServiceServer) {
	// If the following call panics, it indicates UnimplementedViewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ViewService_ServiceDesc, srv)
}

func _ViewService_ListViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).ListViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewService_ListViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).ListViews(ctx, req.(*ListViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewService_GetView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).GetView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewService_GetView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).GetView(ctx, req.(*GetViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewService_CreateView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).CreateView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewService_CreateView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).CreateView(ctx, req.(*CreateViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewService_UpdateView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).UpdateView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewService_UpdateView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).UpdateView(ctx, req.(*UpdateViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewService_DeleteView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).DeleteView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewService_DeleteView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).DeleteView(ctx, req.(*DeleteViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewService_MatchClientToView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).MatchClientToView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewService_MatchClientToView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).MatchClientToView(ctx, req.(*MatchClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewService_AttachZoneToView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).AttachZoneToView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewService_AttachZoneToView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).AttachZoneToView(ctx, req.(*AttachZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewService_DetachZoneFromView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServiceServer).DetachZoneFromView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewService_DetachZoneFromView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServiceServer).DetachZoneFromView(ctx, req.(*DetachZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ViewService_ServiceDesc is the grpc.ServiceDesc for ViewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ViewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsscience.v1.ViewService",
	HandlerType: (*ViewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListViews",
			Handler:    _ViewService_ListViews_Handler,
		},
		{
			MethodName: "GetView",
			Handler:    _ViewService_GetView_Handler,
		},
		{
			MethodName: "CreateView",
			Handler:    _ViewService_CreateView_Handler,
		},
		{
			MethodName: "UpdateView",
			Handler:    _ViewService_UpdateView_Handler,
		},
		{
			MethodName: "DeleteView",
			Handler:    _ViewService_DeleteView_Handler,
		},
		{
			MethodName: "MatchClientToView",
			Handler:    _ViewService_MatchClientToView_Handler,
		},
		{
			MethodName: "AttachZoneToView",
			Handler:    _ViewService_AttachZoneToView_Handler,
		},
		{
			MethodName: "DetachZoneFromView",
			Handler:    _ViewService_DetachZoneFromView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "views.proto",
}
