// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: views.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchType int32

const (
	MatchType_MATCH_TYPE_UNSPECIFIED    MatchType = 0
	MatchType_MATCH_TYPE_SOURCE_IP      MatchType = 1 // Match source IP (CIDR)
	MatchType_MATCH_TYPE_SOURCE_NETWORK MatchType = 2 // Match source network name
	MatchType_MATCH_TYPE_ASN            MatchType = 3 // Match ASN
	MatchType_MATCH_TYPE_COUNTRY        MatchType = 4 // Match GeoIP country
	MatchType_MATCH_TYPE_ACL            MatchType = 5 // Match named ACL
	MatchType_MATCH_TYPE_EDNS_SUBNET    MatchType = 6 // Match EDNS client subnet
	MatchType_MATCH_TYPE_ANY            MatchType = 7 // Match any (default/fallback view)
)

// Enum value maps for MatchType.
var (
	MatchType_name = map[int32]string{
		0: "MATCH_TYPE_UNSPECIFIED",
		1: "MATCH_TYPE_SOURCE_IP",
		2: "MATCH_TYPE_SOURCE_NETWORK",
		3: "MATCH_TYPE_ASN",
		4: "MATCH_TYPE_COUNTRY",
		5: "MATCH_TYPE_ACL",
		6: "MATCH_TYPE_EDNS_SUBNET",
		7: "MATCH_TYPE_ANY",
	}
	MatchType_value = map[string]int32{
		"MATCH_TYPE_UNSPECIFIED":    0,
		"MATCH_TYPE_SOURCE_IP":      1,
		"MATCH_TYPE_SOURCE_NETWORK": 2,
		"MATCH_TYPE_ASN":            3,
		"MATCH_TYPE_COUNTRY":        4,
		"MATCH_TYPE_ACL":            5,
		"MATCH_TYPE_EDNS_SUBNET":    6,
		"MATCH_TYPE_ANY":            7,
	}
)

func (x MatchType) Enum() *MatchType {
	p := new(MatchType)
	*p = x
	return p
}

func (x MatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_views_proto_enumTypes[0].Descriptor()
}

func (MatchType) Type() protoreflect.EnumType {
	return &file_views_proto_enumTypes[0]
}

func (x MatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchType.Descriptor instead.
func (MatchType) EnumDescriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{0}
}

// View represents a DNS view (split-horizon)
type View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // View name (e.g., "internal", "external", "dmz")
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"` // Lower number = higher priority for matching
	MatchClients  []*MatchCriteria       `protobuf:"bytes,4,rep,name=match_clients,json=matchClients,proto3" json:"match_clients,omitempty"`
	Options       *ViewOptions           `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	Zones         []string               `protobuf:"bytes,6,rep,name=zones,proto3" json:"zones,omitempty"` // Zone names attached to this view
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Enabled       bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_views_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{0}
}

func (x *View) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *View) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *View) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *View) GetMatchClients() []*MatchCriteria {
	if x != nil {
		return x.MatchClients
	}
	return nil
}

func (x *View) GetOptions() *ViewOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *View) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *View) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *View) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *View) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// Match criteria for view selection
type MatchCriteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MatchType              `protobuf:"varint,1,opt,name=type,proto3,enum=dnsscience.v1.MatchType" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`    // CIDR, ASN, country code, etc.
	Negate        bool                   `protobuf:"varint,3,opt,name=negate,proto3" json:"negate,omitempty"` // Negate match (NOT)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCriteria) Reset() {
	*x = MatchCriteria{}
	mi := &file_views_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCriteria) ProtoMessage() {}

func (x *MatchCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCriteria.ProtoReflect.Descriptor instead.
func (*MatchCriteria) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{1}
}

func (x *MatchCriteria) GetType() MatchType {
	if x != nil {
		return x.Type
	}
	return MatchType_MATCH_TYPE_UNSPECIFIED
}

func (x *MatchCriteria) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MatchCriteria) GetNegate() bool {
	if x != nil {
		return x.Negate
	}
	return false
}

// View-specific options
type ViewOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recursion     bool                   `protobuf:"varint,1,opt,name=recursion,proto3" json:"recursion,omitempty"`                          // Allow recursion for this view
	Dnssec        bool                   `protobuf:"varint,2,opt,name=dnssec,proto3" json:"dnssec,omitempty"`                                // Enable DNSSEC for this view
	Forwarders    []string               `protobuf:"bytes,3,rep,name=forwarders,proto3" json:"forwarders,omitempty"`                         // Forwarders for this view
	CacheSize     uint32                 `protobuf:"varint,4,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`         // Per-view cache size (MB)
	MaxCacheTtl   uint32                 `protobuf:"varint,5,opt,name=max_cache_ttl,json=maxCacheTtl,proto3" json:"max_cache_ttl,omitempty"` // Maximum cache TTL
	MinCacheTtl   uint32                 `protobuf:"varint,6,opt,name=min_cache_ttl,json=minCacheTtl,proto3" json:"min_cache_ttl,omitempty"` // Minimum cache TTL
	LogQueries    bool                   `protobuf:"varint,7,opt,name=log_queries,json=logQueries,proto3" json:"log_queries,omitempty"`      // Log queries matching this view
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewOptions) Reset() {
	*x = ViewOptions{}
	mi := &file_views_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewOptions) ProtoMessage() {}

func (x *ViewOptions) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewOptions.ProtoReflect.Descriptor instead.
func (*ViewOptions) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{2}
}

func (x *ViewOptions) GetRecursion() bool {
	if x != nil {
		return x.Recursion
	}
	return false
}

func (x *ViewOptions) GetDnssec() bool {
	if x != nil {
		return x.Dnssec
	}
	return false
}

func (x *ViewOptions) GetForwarders() []string {
	if x != nil {
		return x.Forwarders
	}
	return nil
}

func (x *ViewOptions) GetCacheSize() uint32 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

func (x *ViewOptions) GetMaxCacheTtl() uint32 {
	if x != nil {
		return x.MaxCacheTtl
	}
	return 0
}

func (x *ViewOptions) GetMinCacheTtl() uint32 {
	if x != nil {
		return x.MinCacheTtl
	}
	return 0
}

func (x *ViewOptions) GetLogQueries() bool {
	if x != nil {
		return x.LogQueries
	}
	return false
}

type ListViewsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeDisabled bool                   `protobuf:"varint,1,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListViewsRequest) Reset() {
	*x = ListViewsRequest{}
	mi := &file_views_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListViewsRequest) ProtoMessage() {}

func (x *ListViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListViewsRequest.ProtoReflect.Descriptor instead.
func (*ListViewsRequest) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{3}
}

func (x *ListViewsRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type ListViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []*View                `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListViewsResponse) Reset() {
	*x = ListViewsResponse{}
	mi := &file_views_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListViewsResponse) ProtoMessage() {}

func (x *ListViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListViewsResponse.ProtoReflect.Descriptor instead.
func (*ListViewsResponse) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{4}
}

func (x *ListViewsResponse) GetViews() []*View {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *ListViewsResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewRequest) Reset() {
	*x = GetViewRequest{}
	mi := &file_views_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewRequest) ProtoMessage() {}

func (x *GetViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewRequest.ProtoReflect.Descriptor instead.
func (*GetViewRequest) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{5}
}

func (x *GetViewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Stats         *ViewStats             `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewResponse) Reset() {
	*x = GetViewResponse{}
	mi := &file_views_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewResponse) ProtoMessage() {}

func (x *GetViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewResponse.ProtoReflect.Descriptor instead.
func (*GetViewResponse) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{6}
}

func (x *GetViewResponse) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *GetViewResponse) GetStats() *ViewStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetViewResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ViewStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalQueries  int64                  `protobuf:"varint,1,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	CacheHits     int64                  `protobuf:"varint,2,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	CacheMisses   int64                  `protobuf:"varint,3,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	AttachedZones int32                  `protobuf:"varint,4,opt,name=attached_zones,json=attachedZones,proto3" json:"attached_zones,omitempty"`
	LastQuery     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_query,json=lastQuery,proto3" json:"last_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewStats) Reset() {
	*x = ViewStats{}
	mi := &file_views_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewStats) ProtoMessage() {}

func (x *ViewStats) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewStats.ProtoReflect.Descriptor instead.
func (*ViewStats) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{7}
}

func (x *ViewStats) GetTotalQueries() int64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *ViewStats) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *ViewStats) GetCacheMisses() int64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *ViewStats) GetAttachedZones() int32 {
	if x != nil {
		return x.AttachedZones
	}
	return 0
}

func (x *ViewStats) GetLastQuery() *timestamppb.Timestamp {
	if x != nil {
		return x.LastQuery
	}
	return nil
}

type CreateViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	MatchClients  []*MatchCriteria       `protobuf:"bytes,4,rep,name=match_clients,json=matchClients,proto3" json:"match_clients,omitempty"`
	Options       *ViewOptions           `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateViewRequest) Reset() {
	*x = CreateViewRequest{}
	mi := &file_views_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateViewRequest) ProtoMessage() {}

func (x *CreateViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateViewRequest.ProtoReflect.Descriptor instead.
func (*CreateViewRequest) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{8}
}

func (x *CreateViewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateViewRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateViewRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateViewRequest) GetMatchClients() []*MatchCriteria {
	if x != nil {
		return x.MatchClients
	}
	return nil
}

func (x *CreateViewRequest) GetOptions() *ViewOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateViewRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CreateViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateViewResponse) Reset() {
	*x = CreateViewResponse{}
	mi := &file_views_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateViewResponse) ProtoMessage() {}

func (x *CreateViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateViewResponse.ProtoReflect.Descriptor instead.
func (*CreateViewResponse) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{9}
}

func (x *CreateViewResponse) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *CreateViewResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	MatchClients  []*MatchCriteria       `protobuf:"bytes,4,rep,name=match_clients,json=matchClients,proto3" json:"match_clients,omitempty"`
	Options       *ViewOptions           `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateViewRequest) Reset() {
	*x = UpdateViewRequest{}
	mi := &file_views_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateViewRequest) ProtoMessage() {}

func (x *UpdateViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateViewRequest.ProtoReflect.Descriptor instead.
func (*UpdateViewRequest) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateViewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateViewRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateViewRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateViewRequest) GetMatchClients() []*MatchCriteria {
	if x != nil {
		return x.MatchClients
	}
	return nil
}

func (x *UpdateViewRequest) GetOptions() *ViewOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UpdateViewRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateViewResponse) Reset() {
	*x = UpdateViewResponse{}
	mi := &file_views_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateViewResponse) ProtoMessage() {}

func (x *UpdateViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateViewResponse.ProtoReflect.Descriptor instead.
func (*UpdateViewResponse) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateViewResponse) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *UpdateViewResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeleteViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Force delete even if zones are attached
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteViewRequest) Reset() {
	*x = DeleteViewRequest{}
	mi := &file_views_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteViewRequest) ProtoMessage() {}

func (x *DeleteViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteViewRequest.ProtoReflect.Descriptor instead.
func (*DeleteViewRequest) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteViewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteViewRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteViewResponse) Reset() {
	*x = DeleteViewResponse{}
	mi := &file_views_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteViewResponse) ProtoMessage() {}

func (x *DeleteViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteViewResponse.ProtoReflect.Descriptor instead.
func (*DeleteViewResponse) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteViewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteViewResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteViewResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type MatchClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIp      string                 `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientSubnet  string                 `protobuf:"bytes,2,opt,name=client_subnet,json=clientSubnet,proto3" json:"client_subnet,omitempty"` // EDNS client subnet
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchClientRequest) Reset() {
	*x = MatchClientRequest{}
	mi := &file_views_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchClientRequest) ProtoMessage() {}

func (x *MatchClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchClientRequest.ProtoReflect.Descriptor instead.
func (*MatchClientRequest) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{14}
}

func (x *MatchClientRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *MatchClientRequest) GetClientSubnet() string {
	if x != nil {
		return x.ClientSubnet
	}
	return ""
}

func (x *MatchClientRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MatchClientResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ViewName        string                 `protobuf:"bytes,1,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	View            *View                  `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	MatchedCriteria *MatchCriteria         `protobuf:"bytes,3,opt,name=matched_criteria,json=matchedCriteria,proto3" json:"matched_criteria,omitempty"`
	Meta            *ResponseMeta          `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchClientResponse) Reset() {
	*x = MatchClientResponse{}
	mi := &file_views_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchClientResponse) ProtoMessage() {}

func (x *MatchClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchClientResponse.ProtoReflect.Descriptor instead.
func (*MatchClientResponse) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{15}
}

func (x *MatchClientResponse) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *MatchClientResponse) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *MatchClientResponse) GetMatchedCriteria() *MatchCriteria {
	if x != nil {
		return x.MatchedCriteria
	}
	return nil
}

func (x *MatchClientResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type AttachZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewName      string                 `protobuf:"bytes,1,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	ZoneName      string                 `protobuf:"bytes,2,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachZoneRequest) Reset() {
	*x = AttachZoneRequest{}
	mi := &file_views_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachZoneRequest) ProtoMessage() {}

func (x *AttachZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachZoneRequest.ProtoReflect.Descriptor instead.
func (*AttachZoneRequest) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{16}
}

func (x *AttachZoneRequest) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *AttachZoneRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

type AttachZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachZoneResponse) Reset() {
	*x = AttachZoneResponse{}
	mi := &file_views_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachZoneResponse) ProtoMessage() {}

func (x *AttachZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachZoneResponse.ProtoReflect.Descriptor instead.
func (*AttachZoneResponse) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{17}
}

func (x *AttachZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttachZoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AttachZoneResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DetachZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewName      string                 `protobuf:"bytes,1,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	ZoneName      string                 `protobuf:"bytes,2,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachZoneRequest) Reset() {
	*x = DetachZoneRequest{}
	mi := &file_views_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachZoneRequest) ProtoMessage() {}

func (x *DetachZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachZoneRequest.ProtoReflect.Descriptor instead.
func (*DetachZoneRequest) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{18}
}

func (x *DetachZoneRequest) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *DetachZoneRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

type DetachZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachZoneResponse) Reset() {
	*x = DetachZoneResponse{}
	mi := &file_views_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachZoneResponse) ProtoMessage() {}

func (x *DetachZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_views_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachZoneResponse.ProtoReflect.Descriptor instead.
func (*DetachZoneResponse) Descriptor() ([]byte, []int) {
	return file_views_proto_rawDescGZIP(), []int{19}
}

func (x *DetachZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetachZoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DetachZoneResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_views_proto protoreflect.FileDescriptor

const file_views_proto_rawDesc = "" +
	"\n" +
	"\vviews.proto\x12\rdnsscience.v1\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x02\n" +
	"\x04View\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12A\n" +
	"\rmatch_clients\x18\x04 \x03(\v2\x1c.dnsscience.v1.MatchCriteriaR\fmatchClients\x124\n" +
	"\aoptions\x18\x05 \x01(\v2\x1a.dnsscience.v1.ViewOptionsR\aoptions\x12\x14\n" +
	"\x05zones\x18\x06 \x03(\tR\x05zones\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\"k\n" +
	"\rMatchCriteria\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.dnsscience.v1.MatchTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06negate\x18\x03 \x01(\bR\x06negate\"\xeb\x01\n" +
	"\vViewOptions\x12\x1c\n" +
	"\trecursion\x18\x01 \x01(\bR\trecursion\x12\x16\n" +
	"\x06dnssec\x18\x02 \x01(\bR\x06dnssec\x12\x1e\n" +
	"\n" +
	"forwarders\x18\x03 \x03(\tR\n" +
	"forwarders\x12\x1d\n" +
	"\n" +
	"cache_size\x18\x04 \x01(\rR\tcacheSize\x12\"\n" +
	"\rmax_cache_ttl\x18\x05 \x01(\rR\vmaxCacheTtl\x12\"\n" +
	"\rmin_cache_ttl\x18\x06 \x01(\rR\vminCacheTtl\x12\x1f\n" +
	"\vlog_queries\x18\a \x01(\bR\n" +
	"logQueries\"=\n" +
	"\x10ListViewsRequest\x12)\n" +
	"\x10include_disabled\x18\x01 \x01(\bR\x0fincludeDisabled\"o\n" +
	"\x11ListViewsResponse\x12)\n" +
	"\x05views\x18\x01 \x03(\v2\x13.dnsscience.v1.ViewR\x05views\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"$\n" +
	"\x0eGetViewRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x9b\x01\n" +
	"\x0fGetViewResponse\x12'\n" +
	"\x04view\x18\x01 \x01(\v2\x13.dnsscience.v1.ViewR\x04view\x12.\n" +
	"\x05stats\x18\x02 \x01(\v2\x18.dnsscience.v1.ViewStatsR\x05stats\x12/\n" +
	"\x04meta\x18\x03 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"\xd4\x01\n" +
	"\tViewStats\x12#\n" +
	"\rtotal_queries\x18\x01 \x01(\x03R\ftotalQueries\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x02 \x01(\x03R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\x03 \x01(\x03R\vcacheMisses\x12%\n" +
	"\x0eattached_zones\x18\x04 \x01(\x05R\rattachedZones\x129\n" +
	"\n" +
	"last_query\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastQuery\"\xf8\x01\n" +
	"\x11CreateViewRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12A\n" +
	"\rmatch_clients\x18\x04 \x03(\v2\x1c.dnsscience.v1.MatchCriteriaR\fmatchClients\x124\n" +
	"\aoptions\x18\x05 \x01(\v2\x1a.dnsscience.v1.ViewOptionsR\aoptions\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"n\n" +
	"\x12CreateViewResponse\x12'\n" +
	"\x04view\x18\x01 \x01(\v2\x13.dnsscience.v1.ViewR\x04view\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"\xf8\x01\n" +
	"\x11UpdateViewRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12A\n" +
	"\rmatch_clients\x18\x04 \x03(\v2\x1c.dnsscience.v1.MatchCriteriaR\fmatchClients\x124\n" +
	"\aoptions\x18\x05 \x01(\v2\x1a.dnsscience.v1.ViewOptionsR\aoptions\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"n\n" +
	"\x12UpdateViewResponse\x12'\n" +
	"\x04view\x18\x01 \x01(\v2\x13.dnsscience.v1.ViewR\x04view\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"=\n" +
	"\x11DeleteViewRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"y\n" +
	"\x12DeleteViewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04meta\x18\x03 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"\xe0\x01\n" +
	"\x12MatchClientRequest\x12\x1b\n" +
	"\tclient_ip\x18\x01 \x01(\tR\bclientIp\x12#\n" +
	"\rclient_subnet\x18\x02 \x01(\tR\fclientSubnet\x12K\n" +
	"\bmetadata\x18\x03 \x03(\v2/.dnsscience.v1.MatchClientRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\x13MatchClientResponse\x12\x1b\n" +
	"\tview_name\x18\x01 \x01(\tR\bviewName\x12'\n" +
	"\x04view\x18\x02 \x01(\v2\x13.dnsscience.v1.ViewR\x04view\x12G\n" +
	"\x10matched_criteria\x18\x03 \x01(\v2\x1c.dnsscience.v1.MatchCriteriaR\x0fmatchedCriteria\x12/\n" +
	"\x04meta\x18\x04 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"M\n" +
	"\x11AttachZoneRequest\x12\x1b\n" +
	"\tview_name\x18\x01 \x01(\tR\bviewName\x12\x1b\n" +
	"\tzone_name\x18\x02 \x01(\tR\bzoneName\"y\n" +
	"\x12AttachZoneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04meta\x18\x03 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"M\n" +
	"\x11DetachZoneRequest\x12\x1b\n" +
	"\tview_name\x18\x01 \x01(\tR\bviewName\x12\x1b\n" +
	"\tzone_name\x18\x02 \x01(\tR\bzoneName\"y\n" +
	"\x12DetachZoneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04meta\x18\x03 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta*\xd0\x01\n" +
	"\tMatchType\x12\x1a\n" +
	"\x16MATCH_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MATCH_TYPE_SOURCE_IP\x10\x01\x12\x1d\n" +
	"\x19MATCH_TYPE_SOURCE_NETWORK\x10\x02\x12\x12\n" +
	"\x0eMATCH_TYPE_ASN\x10\x03\x12\x16\n" +
	"\x12MATCH_TYPE_COUNTRY\x10\x04\x12\x12\n" +
	"\x0eMATCH_TYPE_ACL\x10\x05\x12\x1a\n" +
	"\x16MATCH_TYPE_EDNS_SUBNET\x10\x06\x12\x12\n" +
	"\x0eMATCH_TYPE_ANY\x10\a2\xb0\x05\n" +
	"\vViewService\x12N\n" +
	"\tListViews\x12\x1f.dnsscience.v1.ListViewsRequest\x1a .dnsscience.v1.ListViewsResponse\x12H\n" +
	"\aGetView\x12\x1d.dnsscience.v1.GetViewRequest\x1a\x1e.dnsscience.v1.GetViewResponse\x12Q\n" +
	"\n" +
	"CreateView\x12 .dnsscience.v1.CreateViewRequest\x1a!.dnsscience.v1.CreateViewResponse\x12Q\n" +
	"\n" +
	"UpdateView\x12 .dnsscience.v1.UpdateViewRequest\x1a!.dnsscience.v1.UpdateViewResponse\x12Q\n" +
	"\n" +
	"DeleteView\x12 .dnsscience.v1.DeleteViewRequest\x1a!.dnsscience.v1.DeleteViewResponse\x12Z\n" +
	"\x11MatchClientToView\x12!.dnsscience.v1.MatchClientRequest\x1a\".dnsscience.v1.MatchClientResponse\x12W\n" +
	"\x10AttachZoneToView\x12 .dnsscience.v1.AttachZoneRequest\x1a!.dnsscience.v1.AttachZoneResponse\x12Y\n" +
	"\x12DetachZoneFromView\x12 .dnsscience.v1.DetachZoneRequest\x1a!.dnsscience.v1.DetachZoneResponseB5Z3github.com/dnsscience/dnsscienced/api/grpc/proto/pbb\x06proto3"

var (
	file_views_proto_rawDescOnce sync.Once
	file_views_proto_rawDescData []byte
)

func file_views_proto_rawDescGZIP() []byte {
	file_views_proto_rawDescOnce.Do(func() {
		file_views_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_views_proto_rawDesc), len(file_views_proto_rawDesc)))
	})
	return file_views_proto_rawDescData
}

var file_views_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_views_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_views_proto_goTypes = []any{
	(MatchType)(0),                // 0: dnsscience.v1.MatchType
	(*View)(nil),                  // 1: dnsscience.v1.View
	(*MatchCriteria)(nil),         // 2: dnsscience.v1.MatchCriteria
	(*ViewOptions)(nil),           // 3: dnsscience.v1.ViewOptions
	(*ListViewsRequest)(nil),      // 4: dnsscience.v1.ListViewsRequest
	(*ListViewsResponse)(nil),     // 5: dnsscience.v1.ListViewsResponse
	(*GetViewRequest)(nil),        // 6: dnsscience.v1.GetViewRequest
	(*GetViewResponse)(nil),       // 7: dnsscience.v1.GetViewResponse
	(*ViewStats)(nil),             // 8: dnsscience.v1.ViewStats
	(*CreateViewRequest)(nil),     // 9: dnsscience.v1.CreateViewRequest
	(*CreateViewResponse)(nil),    // 10: dnsscience.v1.CreateViewResponse
	(*UpdateViewRequest)(nil),     // 11: dnsscience.v1.UpdateViewRequest
	(*UpdateViewResponse)(nil),    // 12: dnsscience.v1.UpdateViewResponse
	(*DeleteViewRequest)(nil),     // 13: dnsscience.v1.DeleteViewRequest
	(*DeleteViewResponse)(nil),    // 14: dnsscience.v1.DeleteViewResponse
	(*MatchClientRequest)(nil),    // 15: dnsscience.v1.MatchClientRequest
	(*MatchClientResponse)(nil),   // 16: dnsscience.v1.MatchClientResponse
	(*AttachZoneRequest)(nil),     // 17: dnsscience.v1.AttachZoneRequest
	(*AttachZoneResponse)(nil),    // 18: dnsscience.v1.AttachZoneResponse
	(*DetachZoneRequest)(nil),     // 19: dnsscience.v1.DetachZoneRequest
	(*DetachZoneResponse)(nil),    // 20: dnsscience.v1.DetachZoneResponse
	nil,                           // 21: dnsscience.v1.MatchClientRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(*ResponseMeta)(nil),          // 23: dnsscience.v1.ResponseMeta
}
var file_views_proto_depIdxs = []int32{
	2,  // 0: dnsscience.v1.View.match_clients:type_name -> dnsscience.v1.MatchCriteria
	3,  // 1: dnsscience.v1.View.options:type_name -> dnsscience.v1.ViewOptions
	22, // 2: dnsscience.v1.View.created_at:type_name -> google.protobuf.Timestamp
	22, // 3: dnsscience.v1.View.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: dnsscience.v1.MatchCriteria.type:type_name -> dnsscience.v1.MatchType
	1,  // 5: dnsscience.v1.ListViewsResponse.views:type_name -> dnsscience.v1.View
	23, // 6: dnsscience.v1.ListViewsResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	1,  // 7: dnsscience.v1.GetViewResponse.view:type_name -> dnsscience.v1.View
	8,  // 8: dnsscience.v1.GetViewResponse.stats:type_name -> dnsscience.v1.ViewStats
	23, // 9: dnsscience.v1.GetViewResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	22, // 10: dnsscience.v1.ViewStats.last_query:type_name -> google.protobuf.Timestamp
	2,  // 11: dnsscience.v1.CreateViewRequest.match_clients:type_name -> dnsscience.v1.MatchCriteria
	3,  // 12: dnsscience.v1.CreateViewRequest.options:type_name -> dnsscience.v1.ViewOptions
	1,  // 13: dnsscience.v1.CreateViewResponse.view:type_name -> dnsscience.v1.View
	23, // 14: dnsscience.v1.CreateViewResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	2,  // 15: dnsscience.v1.UpdateViewRequest.match_clients:type_name -> dnsscience.v1.MatchCriteria
	3,  // 16: dnsscience.v1.UpdateViewRequest.options:type_name -> dnsscience.v1.ViewOptions
	1,  // 17: dnsscience.v1.UpdateViewResponse.view:type_name -> dnsscience.v1.View
	23, // 18: dnsscience.v1.UpdateViewResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	23, // 19: dnsscience.v1.DeleteViewResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	21, // 20: dnsscience.v1.MatchClientRequest.metadata:type_name -> dnsscience.v1.MatchClientRequest.MetadataEntry
	1,  // 21: dnsscience.v1.MatchClientResponse.view:type_name -> dnsscience.v1.View
	2,  // 22: dnsscience.v1.MatchClientResponse.matched_criteria:type_name -> dnsscience.v1.MatchCriteria
	23, // 23: dnsscience.v1.MatchClientResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	23, // 24: dnsscience.v1.AttachZoneResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	23, // 25: dnsscience.v1.DetachZoneResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	4,  // 26: dnsscience.v1.ViewService.ListViews:input_type -> dnsscience.v1.ListViewsRequest
	6,  // 27: dnsscience.v1.ViewService.GetView:input_type -> dnsscience.v1.GetViewRequest
	9,  // 28: dnsscience.v1.ViewService.CreateView:input_type -> dnsscience.v1.CreateViewRequest
	11, // 29: dnsscience.v1.ViewService.UpdateView:input_type -> dnsscience.v1.UpdateViewRequest
	13, // 30: dnsscience.v1.ViewService.DeleteView:input_type -> dnsscience.v1.DeleteViewRequest
	15, // 31: dnsscience.v1.ViewService.MatchClientToView:input_type -> dnsscience.v1.MatchClientRequest
	17, // 32: dnsscience.v1.ViewService.AttachZoneToView:input_type -> dnsscience.v1.AttachZoneRequest
	19, // 33: dnsscience.v1.ViewService.DetachZoneFromView:input_type -> dnsscience.v1.DetachZoneRequest
	5,  // 34: dnsscience.v1.ViewService.ListViews:output_type -> dnsscience.v1.ListViewsResponse
	7,  // 35: dnsscience.v1.ViewService.GetView:output_type -> dnsscience.v1.GetViewResponse
	10, // 36: dnsscience.v1.ViewService.CreateView:output_type -> dnsscience.v1.CreateViewResponse
	12, // 37: dnsscience.v1.ViewService.UpdateView:output_type -> dnsscience.v1.UpdateViewResponse
	14, // 38: dnsscience.v1.ViewService.DeleteView:output_type -> dnsscience.v1.DeleteViewResponse
	16, // 39: dnsscience.v1.ViewService.MatchClientToView:output_type -> dnsscience.v1.MatchClientResponse
	18, // 40: dnsscience.v1.ViewService.AttachZoneToView:output_type -> dnsscience.v1.AttachZoneResponse
	20, // 41: dnsscience.v1.ViewService.DetachZoneFromView:output_type -> dnsscience.v1.DetachZoneResponse
	34, // [34:42] is the sub-list for method output_type
	26, // [26:34] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_views_proto_init() }
func file_views_proto_init() {
	if File_views_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_views_proto_rawDesc), len(file_views_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_views_proto_goTypes,
		DependencyIndexes: file_views_proto_depIdxs,
		EnumInfos:         file_views_proto_enumTypes,
		MessageInfos:      file_views_proto_msgTypes,
	}.Build()
	File_views_proto = out.File
	file_views_proto_goTypes = nil
	file_views_proto_depIdxs = nil
}
