// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: management.proto

package mgmt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateZoneRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Domain         string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Ttl            int32                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Soa            *SOARecord             `protobuf:"bytes,3,opt,name=soa,proto3" json:"soa,omitempty"`
	Nameservers    []string               `protobuf:"bytes,4,rep,name=nameservers,proto3" json:"nameservers,omitempty"`
	InitialRecords map[string]*RecordSet  `protobuf:"bytes,5,rep,name=initial_records,json=initialRecords,proto3" json:"initial_records,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateZoneRequest) Reset() {
	*x = CreateZoneRequest{}
	mi := &file_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateZoneRequest) ProtoMessage() {}

func (x *CreateZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateZoneRequest.ProtoReflect.Descriptor instead.
func (*CreateZoneRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{0}
}

func (x *CreateZoneRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateZoneRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *CreateZoneRequest) GetSoa() *SOARecord {
	if x != nil {
		return x.Soa
	}
	return nil
}

func (x *CreateZoneRequest) GetNameservers() []string {
	if x != nil {
		return x.Nameservers
	}
	return nil
}

func (x *CreateZoneRequest) GetInitialRecords() map[string]*RecordSet {
	if x != nil {
		return x.InitialRecords
	}
	return nil
}

type CreateZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Nameservers   []string               `protobuf:"bytes,3,rep,name=nameservers,proto3" json:"nameservers,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateZoneResponse) Reset() {
	*x = CreateZoneResponse{}
	mi := &file_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateZoneResponse) ProtoMessage() {}

func (x *CreateZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateZoneResponse.ProtoReflect.Descriptor instead.
func (*CreateZoneResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{1}
}

func (x *CreateZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateZoneResponse) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *CreateZoneResponse) GetNameservers() []string {
	if x != nil {
		return x.Nameservers
	}
	return nil
}

func (x *CreateZoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateZoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteZoneRequest) Reset() {
	*x = DeleteZoneRequest{}
	mi := &file_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteZoneRequest) ProtoMessage() {}

func (x *DeleteZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteZoneRequest.ProtoReflect.Descriptor instead.
func (*DeleteZoneRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteZoneRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type DeleteZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteZoneResponse) Reset() {
	*x = DeleteZoneResponse{}
	mi := &file_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteZoneResponse) ProtoMessage() {}

func (x *DeleteZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteZoneResponse.ProtoReflect.Descriptor instead.
func (*DeleteZoneResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteZoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteZoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneRequest) Reset() {
	*x = GetZoneRequest{}
	mi := &file_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneRequest) ProtoMessage() {}

func (x *GetZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneRequest.ProtoReflect.Descriptor instead.
func (*GetZoneRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{4}
}

func (x *GetZoneRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type GetZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Zone          *Zone                  `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneResponse) Reset() {
	*x = GetZoneResponse{}
	mi := &file_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneResponse) ProtoMessage() {}

func (x *GetZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneResponse.ProtoReflect.Descriptor instead.
func (*GetZoneResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{5}
}

func (x *GetZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetZoneResponse) GetZone() *Zone {
	if x != nil {
		return x.Zone
	}
	return nil
}

func (x *GetZoneResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesRequest) Reset() {
	*x = ListZonesRequest{}
	mi := &file_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesRequest) ProtoMessage() {}

func (x *ListZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesRequest.ProtoReflect.Descriptor instead.
func (*ListZonesRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{6}
}

func (x *ListZonesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListZonesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Zones         []*Zone                `protobuf:"bytes,2,rep,name=zones,proto3" json:"zones,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesResponse) Reset() {
	*x = ListZonesResponse{}
	mi := &file_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesResponse) ProtoMessage() {}

func (x *ListZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesResponse.ProtoReflect.Descriptor instead.
func (*ListZonesResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{7}
}

func (x *ListZonesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListZonesResponse) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *ListZonesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListZonesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReloadZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneIds       []string               `protobuf:"bytes,1,rep,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"` // Empty means reload all zones
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadZonesRequest) Reset() {
	*x = ReloadZonesRequest{}
	mi := &file_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadZonesRequest) ProtoMessage() {}

func (x *ReloadZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadZonesRequest.ProtoReflect.Descriptor instead.
func (*ReloadZonesRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{8}
}

func (x *ReloadZonesRequest) GetZoneIds() []string {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

type ReloadZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ZonesReloaded int32                  `protobuf:"varint,2,opt,name=zones_reloaded,json=zonesReloaded,proto3" json:"zones_reloaded,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadZonesResponse) Reset() {
	*x = ReloadZonesResponse{}
	mi := &file_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadZonesResponse) ProtoMessage() {}

func (x *ReloadZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadZonesResponse.ProtoReflect.Descriptor instead.
func (*ReloadZonesResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{9}
}

func (x *ReloadZonesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadZonesResponse) GetZonesReloaded() int32 {
	if x != nil {
		return x.ZonesReloaded
	}
	return 0
}

func (x *ReloadZonesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReloadZonesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Record        *DNSRecord             `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRecordRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *CreateRecordRequest) GetRecord() *DNSRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type CreateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordResponse) Reset() {
	*x = CreateRecordResponse{}
	mi := &file_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordResponse) ProtoMessage() {}

func (x *CreateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateRecordResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRecordResponse) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *CreateRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateRecordResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Record        *DNSRecord             `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRecordRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *UpdateRecordRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *UpdateRecordRequest) GetRecord() *DNSRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordResponse) Reset() {
	*x = UpdateRecordResponse{}
	mi := &file_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordResponse) ProtoMessage() {}

func (x *UpdateRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecordResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateRecordResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRecordRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *DeleteRecordRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type DeleteRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	mi := &file_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecordResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteRecordResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	RecordType    string                 `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"` // Optional filter by type (A, AAAA, CNAME, etc.)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{16}
}

func (x *ListRecordsRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ListRecordsRequest) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *ListRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRecordsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Records       []*DNSRecord           `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{17}
}

func (x *ListRecordsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListRecordsResponse) GetRecords() []*DNSRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListRecordsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRecordsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchCreateRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Records       []*DNSRecord           `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRecordsRequest) Reset() {
	*x = BatchCreateRecordsRequest{}
	mi := &file_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRecordsRequest) ProtoMessage() {}

func (x *BatchCreateRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRecordsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateRecordsRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{18}
}

func (x *BatchCreateRecordsRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *BatchCreateRecordsRequest) GetRecords() []*DNSRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type BatchCreateRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CreatedCount  int32                  `protobuf:"varint,2,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
	RecordIds     []string               `protobuf:"bytes,3,rep,name=record_ids,json=recordIds,proto3" json:"record_ids,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRecordsResponse) Reset() {
	*x = BatchCreateRecordsResponse{}
	mi := &file_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRecordsResponse) ProtoMessage() {}

func (x *BatchCreateRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRecordsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateRecordsResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{19}
}

func (x *BatchCreateRecordsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchCreateRecordsResponse) GetCreatedCount() int32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

func (x *BatchCreateRecordsResponse) GetRecordIds() []string {
	if x != nil {
		return x.RecordIds
	}
	return nil
}

func (x *BatchCreateRecordsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BatchCreateRecordsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BatchUpdateRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Updates       []*RecordUpdate        `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateRecordsRequest) Reset() {
	*x = BatchUpdateRecordsRequest{}
	mi := &file_management_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateRecordsRequest) ProtoMessage() {}

func (x *BatchUpdateRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateRecordsRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateRecordsRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{20}
}

func (x *BatchUpdateRecordsRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *BatchUpdateRecordsRequest) GetUpdates() []*RecordUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type BatchUpdateRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedCount  int32                  `protobuf:"varint,2,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateRecordsResponse) Reset() {
	*x = BatchUpdateRecordsResponse{}
	mi := &file_management_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateRecordsResponse) ProtoMessage() {}

func (x *BatchUpdateRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateRecordsResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateRecordsResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{21}
}

func (x *BatchUpdateRecordsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchUpdateRecordsResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *BatchUpdateRecordsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BatchUpdateRecordsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BatchDeleteRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	RecordIds     []string               `protobuf:"bytes,2,rep,name=record_ids,json=recordIds,proto3" json:"record_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteRecordsRequest) Reset() {
	*x = BatchDeleteRecordsRequest{}
	mi := &file_management_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteRecordsRequest) ProtoMessage() {}

func (x *BatchDeleteRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteRecordsRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteRecordsRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{22}
}

func (x *BatchDeleteRecordsRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *BatchDeleteRecordsRequest) GetRecordIds() []string {
	if x != nil {
		return x.RecordIds
	}
	return nil
}

type BatchDeleteRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteRecordsResponse) Reset() {
	*x = BatchDeleteRecordsResponse{}
	mi := &file_management_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteRecordsResponse) ProtoMessage() {}

func (x *BatchDeleteRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteRecordsResponse.ProtoReflect.Descriptor instead.
func (*BatchDeleteRecordsResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{23}
}

func (x *BatchDeleteRecordsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchDeleteRecordsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *BatchDeleteRecordsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BatchDeleteRecordsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_management_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{24}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ServerName    string                 `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_management_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{25}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type GetServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatusRequest) Reset() {
	*x = GetServerStatusRequest{}
	mi := &file_management_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusRequest) ProtoMessage() {}

func (x *GetServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{26}
}

type GetServerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        *ServerStatus          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatusResponse) Reset() {
	*x = GetServerStatusResponse{}
	mi := &file_management_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatusResponse) ProtoMessage() {}

func (x *GetServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{27}
}

func (x *GetServerStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetServerStatusResponse) GetStatus() *ServerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetServerStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Soa           *SOARecord             `protobuf:"bytes,4,opt,name=soa,proto3" json:"soa,omitempty"`
	Nameservers   []string               `protobuf:"bytes,5,rep,name=nameservers,proto3" json:"nameservers,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	DnssecEnabled bool                   `protobuf:"varint,7,opt,name=dnssec_enabled,json=dnssecEnabled,proto3" json:"dnssec_enabled,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RecordCount   int32                  `protobuf:"varint,10,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_management_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{28}
}

func (x *Zone) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Zone) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *Zone) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Zone) GetSoa() *SOARecord {
	if x != nil {
		return x.Soa
	}
	return nil
}

func (x *Zone) GetNameservers() []string {
	if x != nil {
		return x.Nameservers
	}
	return nil
}

func (x *Zone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Zone) GetDnssecEnabled() bool {
	if x != nil {
		return x.DnssecEnabled
	}
	return false
}

func (x *Zone) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Zone) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Zone) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

type SOARecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryNs     string                 `protobuf:"bytes,1,opt,name=primary_ns,json=primaryNs,proto3" json:"primary_ns,omitempty"`
	Contact       string                 `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	Serial        int64                  `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Refresh       int32                  `protobuf:"varint,4,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Retry         int32                  `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	Expire        int32                  `protobuf:"varint,6,opt,name=expire,proto3" json:"expire,omitempty"`
	NegativeTtl   int32                  `protobuf:"varint,7,opt,name=negative_ttl,json=negativeTtl,proto3" json:"negative_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SOARecord) Reset() {
	*x = SOARecord{}
	mi := &file_management_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SOARecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOARecord) ProtoMessage() {}

func (x *SOARecord) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOARecord.ProtoReflect.Descriptor instead.
func (*SOARecord) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{29}
}

func (x *SOARecord) GetPrimaryNs() string {
	if x != nil {
		return x.PrimaryNs
	}
	return ""
}

func (x *SOARecord) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *SOARecord) GetSerial() int64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *SOARecord) GetRefresh() int32 {
	if x != nil {
		return x.Refresh
	}
	return 0
}

func (x *SOARecord) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *SOARecord) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *SOARecord) GetNegativeTtl() int32 {
	if x != nil {
		return x.NegativeTtl
	}
	return 0
}

type DNSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RecordType    string                 `protobuf:"bytes,3,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Ttl           int32                  `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight        int32                  `protobuf:"varint,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Port          int32                  `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"`
	Proxied       bool                   `protobuf:"varint,9,opt,name=proxied,proto3" json:"proxied,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_management_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{30}
}

func (x *DNSRecord) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *DNSRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSRecord) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *DNSRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DNSRecord) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *DNSRecord) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DNSRecord) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DNSRecord) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DNSRecord) GetProxied() bool {
	if x != nil {
		return x.Proxied
	}
	return false
}

func (x *DNSRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RecordSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSet) Reset() {
	*x = RecordSet{}
	mi := &file_management_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSet) ProtoMessage() {}

func (x *RecordSet) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSet.ProtoReflect.Descriptor instead.
func (*RecordSet) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{31}
}

func (x *RecordSet) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RecordUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Record        *DNSRecord             `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordUpdate) Reset() {
	*x = RecordUpdate{}
	mi := &file_management_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUpdate) ProtoMessage() {}

func (x *RecordUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUpdate.ProtoReflect.Descriptor instead.
func (*RecordUpdate) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{32}
}

func (x *RecordUpdate) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *RecordUpdate) GetRecord() *DNSRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type ServerStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerName       string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ZonesLoaded      int32                  `protobuf:"varint,4,opt,name=zones_loaded,json=zonesLoaded,proto3" json:"zones_loaded,omitempty"`
	TotalRecords     int32                  `protobuf:"varint,5,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	QueriesPerSecond int64                  `protobuf:"varint,6,opt,name=queries_per_second,json=queriesPerSecond,proto3" json:"queries_per_second,omitempty"`
	MemoryUsageMb    float64                `protobuf:"fixed64,7,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	CpuUsagePercent  float64                `protobuf:"fixed64,8,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	LastReload       string                 `protobuf:"bytes,9,opt,name=last_reload,json=lastReload,proto3" json:"last_reload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_management_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_management_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_management_proto_rawDescGZIP(), []int{33}
}

func (x *ServerStatus) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServerStatus) GetZonesLoaded() int32 {
	if x != nil {
		return x.ZonesLoaded
	}
	return 0
}

func (x *ServerStatus) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *ServerStatus) GetQueriesPerSecond() int64 {
	if x != nil {
		return x.QueriesPerSecond
	}
	return 0
}

func (x *ServerStatus) GetMemoryUsageMb() float64 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *ServerStatus) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ServerStatus) GetLastReload() string {
	if x != nil {
		return x.LastReload
	}
	return ""
}

var File_management_proto protoreflect.FileDescriptor

const file_management_proto_rawDesc = "" +
	"\n" +
	"\x10management.proto\x12\vdnsscienced\"\xc1\x02\n" +
	"\x11CreateZoneRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x05R\x03ttl\x12(\n" +
	"\x03soa\x18\x03 \x01(\v2\x16.dnsscienced.SOARecordR\x03soa\x12 \n" +
	"\vnameservers\x18\x04 \x03(\tR\vnameservers\x12[\n" +
	"\x0finitial_records\x18\x05 \x03(\v22.dnsscienced.CreateZoneRequest.InitialRecordsEntryR\x0einitialRecords\x1aY\n" +
	"\x13InitialRecordsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.dnsscienced.RecordSetR\x05value:\x028\x01\"\x99\x01\n" +
	"\x12CreateZoneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\x12 \n" +
	"\vnameservers\x18\x03 \x03(\tR\vnameservers\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\",\n" +
	"\x11DeleteZoneRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\"^\n" +
	"\x12DeleteZoneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\")\n" +
	"\x0eGetZoneRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\"h\n" +
	"\x0fGetZoneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x04zone\x18\x02 \x01(\v2\x11.dnsscienced.ZoneR\x04zone\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"@\n" +
	"\x10ListZonesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\x82\x01\n" +
	"\x11ListZonesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x05zones\x18\x02 \x03(\v2\x11.dnsscienced.ZoneR\x05zones\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"/\n" +
	"\x12ReloadZonesRequest\x12\x19\n" +
	"\bzone_ids\x18\x01 \x03(\tR\azoneIds\"\x86\x01\n" +
	"\x13ReloadZonesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ezones_reloaded\x18\x02 \x01(\x05R\rzonesReloaded\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"^\n" +
	"\x13CreateRecordRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12.\n" +
	"\x06record\x18\x02 \x01(\v2\x16.dnsscienced.DNSRecordR\x06record\"}\n" +
	"\x14CreateRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"{\n" +
	"\x13UpdateRecordRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12.\n" +
	"\x06record\x18\x03 \x01(\v2\x16.dnsscienced.DNSRecordR\x06record\"`\n" +
	"\x14UpdateRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"K\n" +
	"\x13DeleteRecordRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\"`\n" +
	"\x14DeleteRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"|\n" +
	"\x12ListRecordsRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1f\n" +
	"\vrecord_type\x18\x02 \x01(\tR\n" +
	"recordType\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x8d\x01\n" +
	"\x13ListRecordsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\arecords\x18\x02 \x03(\v2\x16.dnsscienced.DNSRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"f\n" +
	"\x19BatchCreateRecordsRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x120\n" +
	"\arecords\x18\x02 \x03(\v2\x16.dnsscienced.DNSRecordR\arecords\"\xac\x01\n" +
	"\x1aBatchCreateRecordsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rcreated_count\x18\x02 \x01(\x05R\fcreatedCount\x12\x1d\n" +
	"\n" +
	"record_ids\x18\x03 \x03(\tR\trecordIds\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"i\n" +
	"\x19BatchUpdateRecordsRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x123\n" +
	"\aupdates\x18\x02 \x03(\v2\x19.dnsscienced.RecordUpdateR\aupdates\"\x8d\x01\n" +
	"\x1aBatchUpdateRecordsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rupdated_count\x18\x02 \x01(\x05R\fupdatedCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"S\n" +
	"\x19BatchDeleteRecordsRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1d\n" +
	"\n" +
	"record_ids\x18\x02 \x03(\tR\trecordIds\"\x8d\x01\n" +
	"\x1aBatchDeleteRecordsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthCheckRequest\"\x91\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\"\x18\n" +
	"\x16GetServerStatusRequest\"|\n" +
	"\x17GetServerStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.dnsscienced.ServerStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xb5\x02\n" +
	"\x04Zone\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\x12(\n" +
	"\x03soa\x18\x04 \x01(\v2\x16.dnsscienced.SOARecordR\x03soa\x12 \n" +
	"\vnameservers\x18\x05 \x03(\tR\vnameservers\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0ednssec_enabled\x18\a \x01(\bR\rdnssecEnabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12!\n" +
	"\frecord_count\x18\n" +
	" \x01(\x05R\vrecordCount\"\xc7\x01\n" +
	"\tSOARecord\x12\x1d\n" +
	"\n" +
	"primary_ns\x18\x01 \x01(\tR\tprimaryNs\x12\x18\n" +
	"\acontact\x18\x02 \x01(\tR\acontact\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\x03R\x06serial\x12\x18\n" +
	"\arefresh\x18\x04 \x01(\x05R\arefresh\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x05R\x05retry\x12\x16\n" +
	"\x06expire\x18\x06 \x01(\x05R\x06expire\x12!\n" +
	"\fnegative_ttl\x18\a \x01(\x05R\vnegativeTtl\"\xea\x02\n" +
	"\tDNSRecord\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vrecord_type\x18\x03 \x01(\tR\n" +
	"recordType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\x05R\x03ttl\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06weight\x18\a \x01(\x05R\x06weight\x12\x12\n" +
	"\x04port\x18\b \x01(\x05R\x04port\x12\x18\n" +
	"\aproxied\x18\t \x01(\bR\aproxied\x12@\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2$.dnsscienced.DNSRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\tRecordSet\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"[\n" +
	"\fRecordUpdate\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12.\n" +
	"\x06record\x18\x02 \x01(\v2\x16.dnsscienced.DNSRecordR\x06record\"\xdb\x02\n" +
	"\fServerStatus\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fzones_loaded\x18\x04 \x01(\x05R\vzonesLoaded\x12#\n" +
	"\rtotal_records\x18\x05 \x01(\x05R\ftotalRecords\x12,\n" +
	"\x12queries_per_second\x18\x06 \x01(\x03R\x10queriesPerSecond\x12&\n" +
	"\x0fmemory_usage_mb\x18\a \x01(\x01R\rmemoryUsageMb\x12*\n" +
	"\x11cpu_usage_percent\x18\b \x01(\x01R\x0fcpuUsagePercent\x12\x1f\n" +
	"\vlast_reload\x18\t \x01(\tR\n" +
	"lastReload2\xcb\t\n" +
	"\x11ManagementService\x12M\n" +
	"\n" +
	"CreateZone\x12\x1e.dnsscienced.CreateZoneRequest\x1a\x1f.dnsscienced.CreateZoneResponse\x12M\n" +
	"\n" +
	"DeleteZone\x12\x1e.dnsscienced.DeleteZoneRequest\x1a\x1f.dnsscienced.DeleteZoneResponse\x12D\n" +
	"\aGetZone\x12\x1b.dnsscienced.GetZoneRequest\x1a\x1c.dnsscienced.GetZoneResponse\x12J\n" +
	"\tListZones\x12\x1d.dnsscienced.ListZonesRequest\x1a\x1e.dnsscienced.ListZonesResponse\x12P\n" +
	"\vReloadZones\x12\x1f.dnsscienced.ReloadZonesRequest\x1a .dnsscienced.ReloadZonesResponse\x12S\n" +
	"\fCreateRecord\x12 .dnsscienced.CreateRecordRequest\x1a!.dnsscienced.CreateRecordResponse\x12S\n" +
	"\fUpdateRecord\x12 .dnsscienced.UpdateRecordRequest\x1a!.dnsscienced.UpdateRecordResponse\x12S\n" +
	"\fDeleteRecord\x12 .dnsscienced.DeleteRecordRequest\x1a!.dnsscienced.DeleteRecordResponse\x12P\n" +
	"\vListRecords\x12\x1f.dnsscienced.ListRecordsRequest\x1a .dnsscienced.ListRecordsResponse\x12e\n" +
	"\x12BatchCreateRecords\x12&.dnsscienced.BatchCreateRecordsRequest\x1a'.dnsscienced.BatchCreateRecordsResponse\x12e\n" +
	"\x12BatchUpdateRecords\x12&.dnsscienced.BatchUpdateRecordsRequest\x1a'.dnsscienced.BatchUpdateRecordsResponse\x12e\n" +
	"\x12BatchDeleteRecords\x12&.dnsscienced.BatchDeleteRecordsRequest\x1a'.dnsscienced.BatchDeleteRecordsResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.dnsscienced.HealthCheckRequest\x1a .dnsscienced.HealthCheckResponse\x12\\\n" +
	"\x0fGetServerStatus\x12#.dnsscienced.GetServerStatusRequest\x1a$.dnsscienced.GetServerStatusResponseB:Z8github.com/dnsscience/dnsscienced/api/grpc/proto/pb/mgmtb\x06proto3"

var (
	file_management_proto_rawDescOnce sync.Once
	file_management_proto_rawDescData []byte
)

func file_management_proto_rawDescGZIP() []byte {
	file_management_proto_rawDescOnce.Do(func() {
		file_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)))
	})
	return file_management_proto_rawDescData
}

var file_management_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_management_proto_goTypes = []any{
	(*CreateZoneRequest)(nil),          // 0: dnsscienced.CreateZoneRequest
	(*CreateZoneResponse)(nil),         // 1: dnsscienced.CreateZoneResponse
	(*DeleteZoneRequest)(nil),          // 2: dnsscienced.DeleteZoneRequest
	(*DeleteZoneResponse)(nil),         // 3: dnsscienced.DeleteZoneResponse
	(*GetZoneRequest)(nil),             // 4: dnsscienced.GetZoneRequest
	(*GetZoneResponse)(nil),            // 5: dnsscienced.GetZoneResponse
	(*ListZonesRequest)(nil),           // 6: dnsscienced.ListZonesRequest
	(*ListZonesResponse)(nil),          // 7: dnsscienced.ListZonesResponse
	(*ReloadZonesRequest)(nil),         // 8: dnsscienced.ReloadZonesRequest
	(*ReloadZonesResponse)(nil),        // 9: dnsscienced.ReloadZonesResponse
	(*CreateRecordRequest)(nil),        // 10: dnsscienced.CreateRecordRequest
	(*CreateRecordResponse)(nil),       // 11: dnsscienced.CreateRecordResponse
	(*UpdateRecordRequest)(nil),        // 12: dnsscienced.UpdateRecordRequest
	(*UpdateRecordResponse)(nil),       // 13: dnsscienced.UpdateRecordResponse
	(*DeleteRecordRequest)(nil),        // 14: dnsscienced.DeleteRecordRequest
	(*DeleteRecordResponse)(nil),       // 15: dnsscienced.DeleteRecordResponse
	(*ListRecordsRequest)(nil),         // 16: dnsscienced.ListRecordsRequest
	(*ListRecordsResponse)(nil),        // 17: dnsscienced.ListRecordsResponse
	(*BatchCreateRecordsRequest)(nil),  // 18: dnsscienced.BatchCreateRecordsRequest
	(*BatchCreateRecordsResponse)(nil), // 19: dnsscienced.BatchCreateRecordsResponse
	(*BatchUpdateRecordsRequest)(nil),  // 20: dnsscienced.BatchUpdateRecordsRequest
	(*BatchUpdateRecordsResponse)(nil), // 21: dnsscienced.BatchUpdateRecordsResponse
	(*BatchDeleteRecordsRequest)(nil),  // 22: dnsscienced.BatchDeleteRecordsRequest
	(*BatchDeleteRecordsResponse)(nil), // 23: dnsscienced.BatchDeleteRecordsResponse
	(*HealthCheckRequest)(nil),         // 24: dnsscienced.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 25: dnsscienced.HealthCheckResponse
	(*GetServerStatusRequest)(nil),     // 26: dnsscienced.GetServerStatusRequest
	(*GetServerStatusResponse)(nil),    // 27: dnsscienced.GetServerStatusResponse
	(*Zone)(nil),                       // 28: dnsscienced.Zone
	(*SOARecord)(nil),                  // 29: dnsscienced.SOARecord
	(*DNSRecord)(nil),                  // 30: dnsscienced.DNSRecord
	(*RecordSet)(nil),                  // 31: dnsscienced.RecordSet
	(*RecordUpdate)(nil),               // 32: dnsscienced.RecordUpdate
	(*ServerStatus)(nil),               // 33: dnsscienced.ServerStatus
	nil,                                // 34: dnsscienced.CreateZoneRequest.InitialRecordsEntry
	nil,                                // 35: dnsscienced.DNSRecord.MetadataEntry
}
var file_management_proto_depIdxs = []int32{
	29, // 0: dnsscienced.CreateZoneRequest.soa:type_name -> dnsscienced.SOARecord
	34, // 1: dnsscienced.CreateZoneRequest.initial_records:type_name -> dnsscienced.CreateZoneRequest.InitialRecordsEntry
	28, // 2: dnsscienced.GetZoneResponse.zone:type_name -> dnsscienced.Zone
	28, // 3: dnsscienced.ListZonesResponse.zones:type_name -> dnsscienced.Zone
	30, // 4: dnsscienced.CreateRecordRequest.record:type_name -> dnsscienced.DNSRecord
	30, // 5: dnsscienced.UpdateRecordRequest.record:type_name -> dnsscienced.DNSRecord
	30, // 6: dnsscienced.ListRecordsResponse.records:type_name -> dnsscienced.DNSRecord
	30, // 7: dnsscienced.BatchCreateRecordsRequest.records:type_name -> dnsscienced.DNSRecord
	32, // 8: dnsscienced.BatchUpdateRecordsRequest.updates:type_name -> dnsscienced.RecordUpdate
	33, // 9: dnsscienced.GetServerStatusResponse.status:type_name -> dnsscienced.ServerStatus
	29, // 10: dnsscienced.Zone.soa:type_name -> dnsscienced.SOARecord
	35, // 11: dnsscienced.DNSRecord.metadata:type_name -> dnsscienced.DNSRecord.MetadataEntry
	30, // 12: dnsscienced.RecordUpdate.record:type_name -> dnsscienced.DNSRecord
	31, // 13: dnsscienced.CreateZoneRequest.InitialRecordsEntry.value:type_name -> dnsscienced.RecordSet
	0,  // 14: dnsscienced.ManagementService.CreateZone:input_type -> dnsscienced.CreateZoneRequest
	2,  // 15: dnsscienced.ManagementService.DeleteZone:input_type -> dnsscienced.DeleteZoneRequest
	4,  // 16: dnsscienced.ManagementService.GetZone:input_type -> dnsscienced.GetZoneRequest
	6,  // 17: dnsscienced.ManagementService.ListZones:input_type -> dnsscienced.ListZonesRequest
	8,  // 18: dnsscienced.ManagementService.ReloadZones:input_type -> dnsscienced.ReloadZonesRequest
	10, // 19: dnsscienced.ManagementService.CreateRecord:input_type -> dnsscienced.CreateRecordRequest
	12, // 20: dnsscienced.ManagementService.UpdateRecord:input_type -> dnsscienced.UpdateRecordRequest
	14, // 21: dnsscienced.ManagementService.DeleteRecord:input_type -> dnsscienced.DeleteRecordRequest
	16, // 22: dnsscienced.ManagementService.ListRecords:input_type -> dnsscienced.ListRecordsRequest
	18, // 23: dnsscienced.ManagementService.BatchCreateRecords:input_type -> dnsscienced.BatchCreateRecordsRequest
	20, // 24: dnsscienced.ManagementService.BatchUpdateRecords:input_type -> dnsscienced.BatchUpdateRecordsRequest
	22, // 25: dnsscienced.ManagementService.BatchDeleteRecords:input_type -> dnsscienced.BatchDeleteRecordsRequest
	24, // 26: dnsscienced.ManagementService.HealthCheck:input_type -> dnsscienced.HealthCheckRequest
	26, // 27: dnsscienced.ManagementService.GetServerStatus:input_type -> dnsscienced.GetServerStatusRequest
	1,  // 28: dnsscienced.ManagementService.CreateZone:output_type -> dnsscienced.CreateZoneResponse
	3,  // 29: dnsscienced.ManagementService.DeleteZone:output_type -> dnsscienced.DeleteZoneResponse
	5,  // 30: dnsscienced.ManagementService.GetZone:output_type -> dnsscienced.GetZoneResponse
	7,  // 31: dnsscienced.ManagementService.ListZones:output_type -> dnsscienced.ListZonesResponse
	9,  // 32: dnsscienced.ManagementService.ReloadZones:output_type -> dnsscienced.ReloadZonesResponse
	11, // 33: dnsscienced.ManagementService.CreateRecord:output_type -> dnsscienced.CreateRecordResponse
	13, // 34: dnsscienced.ManagementService.UpdateRecord:output_type -> dnsscienced.UpdateRecordResponse
	15, // 35: dnsscienced.ManagementService.DeleteRecord:output_type -> dnsscienced.DeleteRecordResponse
	17, // 36: dnsscienced.ManagementService.ListRecords:output_type -> dnsscienced.ListRecordsResponse
	19, // 37: dnsscienced.ManagementService.BatchCreateRecords:output_type -> dnsscienced.BatchCreateRecordsResponse
	21, // 38: dnsscienced.ManagementService.BatchUpdateRecords:output_type -> dnsscienced.BatchUpdateRecordsResponse
	23, // 39: dnsscienced.ManagementService.BatchDeleteRecords:output_type -> dnsscienced.BatchDeleteRecordsResponse
	25, // 40: dnsscienced.ManagementService.HealthCheck:output_type -> dnsscienced.HealthCheckResponse
	27, // 41: dnsscienced.ManagementService.GetServerStatus:output_type -> dnsscienced.GetServerStatusResponse
	28, // [28:42] is the sub-list for method output_type
	14, // [14:28] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_management_proto_init() }
func file_management_proto_init() {
	if File_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_proto_rawDesc), len(file_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_proto_goTypes,
		DependencyIndexes: file_management_proto_depIdxs,
		MessageInfos:      file_management_proto_msgTypes,
	}.Build()
	File_management_proto = out.File
	file_management_proto_goTypes = nil
	file_management_proto_depIdxs = nil
}
